### ISSUE TITLE
应用配置时崩溃

### ISSUE THREAD

**Issue by XiaoQiAWA** [MCModderAnchor/TACZ#10]
应用配置时有概率崩溃 1.0.0 Hotfix2 beta
[crash-2024-06-03_19.24.20-client.txt](https://github.com/user-attachments/files/15533086/crash-2024-06-03_19.24.20-client.txt)
[latest.log](https://github.com/user-attachments/files/15533194/latest.log)
[debug.log](https://github.com/user-attachments/files/15533198/debug.log)
模组列表：
Cloth Config API | 11.1.118
Embeddium | 0.3.19+mc1.20.1
TaC: 绿葡萄附属包|TaC:LesRaisins Append Pack 0.2.1
Oculus | 1.7.0
Timeless and Classics Zero | 1.0.0-hotfix2
Xaero的小地图 | Xaero's Minimap |完整版|24.1.1
Xaero的世界地图|Xaero's World Map | 1.38.4

**Comment by XiaoQiAWA** [comment]
我的日志好像有一堆废话😮（没删干净的其他模组报错）

**Comment by xjqsh** [comment]
你有没有在打开配置文件的时候按菜单的保存配置?

**Comment by Litt1eBai** [comment]
[crash-2024-06-04_01.20.29-client.txt](https://github.com/user-attachments/files/15537419/crash-2024-06-04_01.20.29-client.txt)
[debug.log](https://github.com/user-attachments/files/15537421/debug.log)
[latest.log](https://github.com/user-attachments/files/15537423/latest.log)
复现出同样问题,Cloth Config API 无论版本是 V10 还是 V12 都存在同样的问题.
![image](https://github.com/MCModderAnchor/TACZ/assets/86658250/7638333e-b364-4dec-9af8-39d82ad00304)
主界面修改设置后,点击完成并退出就会崩溃

**Comment by TartaricAcid** [comment]
你是游戏内按 Alt T 快捷键打开的这个界面，还是游戏外点击 mods 按钮打开的界面

**Comment by Litt1eBai** [comment]
\

> 你是游戏内按 Alt T 快捷键打开的这个界面，还是游戏外点击 mods 按钮打开的界面

游戏外的 mods 按钮打开的界面会出现这样的问题,游戏内 atl + T 不会出现

**Comment by TartaricAcid** [comment]
已在 hotfix4 中修复
