### ISSUE TITLE
Memory leak when paired with "Ice and Fire"

### ISSUE THREAD

**Issue by IcyG1045** [MCModderAnchor/TACZ#101]
When running with the "Ice and Fire" mod, if a dragon skull is on the ground and you obtain a rifle from crafting or creative, holding the rifle makes the dragon skull disappear. It additionally causes a memory leak and after a short period of time, the game will crash with the error message "insufficient memory".

**Comment by TartaricAcid** [comment]
Did you use the shadow?

**Comment by 286799714** [comment]
Currently tacz cannot work well with bliss and photon
