### ISSUE TITLE
bug on DB-4 Ursus

### ISSUE THREAD

**Issue by n0links** [MCModderAnchor/TACZ#108]
the  DB-4 URSUS have in the description a bug 
 the text hace a cut
![Captura de pantalla 2024-07-13 202654](https://github.com/user-attachments/assets/41a5d55a-d7b2-48df-baae-411653ba9451)
i dont think its my  problem

**Comment by n0links** [comment]
> the DB-4 URSUS have in the description a bug the text hace a cut ![Captura de pantalla 2024-07-13 202654](https://private-user-images.githubusercontent.com/175503861/348496320-41a5d55a-d7b2-48df-baae-411653ba9451.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4OTU2MTEsIm5iZiI6MTcyMDg5NTMxMSwicGF0aCI6Ii8xNzU1MDM4NjEvMzQ4NDk2MzIwLTQxYTVkNTVhLWQ3YjItNDhkZi1iYWFlLTQxMTY1M2JhOTQ1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QxODI4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmVjYzMzYWMxZGZlYTRmZWM2NTM5YWJiNTQ0YzJhY2M0MDIzNmMxODNlZmM1ZTBmYTUwYmYyNWVkZTQ5YzQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h7s5Zl5hR607mKOwe3A7_ua0Vxm3wEtRlE5uqHrJpU0) i dont think its my problem only past in spanish lenguage

**Comment by TartaricAcid** [comment]
In order to prevent some people from writing long text messages

We have set a length limit for gun tooltip messages
