### ISSUE TITLE
/give ammo

### ISSUE THREAD

**Issue by BkBUNCH** [MCModderAnchor/TACZ#110]
How do you do the /give ammo since it won't let me I'm trying to get 9mm

**Comment by 286799714** [comment]
https://github.com/MCModderAnchor/TACZ/issues/76
/give @p tacz:ammo{AmmoId:"tacz:9mm"}

**Comment by Spedias** [comment]
Where can I find those NBT tags for the specific items, like "tacz:9mm" and so on? I've tried F3+H, but it only gives the generic NBT tag used for all the items of that category.

**Comment by JosephAlanLane** [comment]
tacz\tacz_default_gun\data\tacz\data\guns

**Comment by ANTowski-1** [comment]
the tags like "tacz:9mm" could be toggled on like any other tags (like minecraft:iron_ore) in the seetings (it is in accesibility settins)
