### ISSUE TITLE
1.0.2 Release tacz config not updating to new version

### ISSUE THREAD

**Issue by ArcticCrow** [MCModderAnchor/TACZ#116]
I notice that there was new guns/variants added and when i loaded up the new update their wasn't any of them added until i took the custom tacz folder from the file and put it in the config itself.

**Comment by F1zeiL** [comment]
> I notice that there was new guns/variants added and when i loaded up the new update their wasn't any of them added until i took the custom tacz folder from the file and put it in the config itself.

You need to disable the DefaultPackDebug in tacz-common.toml, then when you use the /tacz reload command in-game, the new resources will sync to the custom folder. But remember to copy your original custom files to avoid being overwritten by sync.
