### ISSUE TITLE
原版枪包中的枪无法开枪

### ISSUE THREAD

**Issue by 534019023** [MCModderAnchor/TACZ#118]
版本是1.0.2beta版，最开始的时候能用，自从朋友把服务器跑图跑崩了后就出现bug了，所有原版枪包中的枪都开不了枪，并且换弹时第三人称没有动作，第三方枪包中的枪都正常，目前更新到1.0.2release版后bug依然存在，并且单人游戏中没遇到这个bug

**Comment by 534019023** [comment]
原版子弹出现了无法叠放的bug，一个子弹占一个格子，而且放不进弹药箱

**Comment by F1zeiL** [comment]
> 原版子弹出现了无法叠放的bug，一个子弹占一个格子，而且放不进弹药箱

你们是否有添加提升堆叠上限的模组？如果有，请说一下是哪一个，因为有的提升堆叠的模组本身具有很差的兼容性。

**Comment by 534019023** [comment]
> > 原版子弹出现了无法叠放的bug，一个子弹占一个格子，而且放不进弹药箱
> 
> 你们是否有添加提升堆叠上限的模组？如果有，请说一下是哪一个，因为有的提升堆叠的模组本身具有很差的兼容性。

没有加堆叠的mod，刚才我把服务器里config里的两个default文件夹和tacz-common.toml和tacz-server.toml删了后重启服务器解决了这个bug，我觉得可能是炸服的时候导致两个default文件夹里的文件出了问题
