### ISSUE TITLE
/give specific gun with specific firemode

### ISSUE THREAD

**Issue by BreadEaterYT** [MCModderAnchor/TACZ#119]
Hello, ive got a issue where when i give myself a gun with /give @p tacz:modern_kinetic_gun{GunId:"tacz:ak47"} but when i fire it says unknown firemode, how i can set the firemode in the give commands ?

(please reply via mail or discord cuz i go on github very rarely, mail: contact@breadeater.fr, discord: bread_eater_yt)

**Comment by HeavyArtilleryTank** [comment]
you need to use {GunFireMode: "SEMI or AUTO or BURST",
