### ISSUE TITLE
与oculus的兼容性问题

### ISSUE THREAD

**Issue by fmys2010** [MCModderAnchor/TACZ#120]
似乎在一些情况下，将Tacz与oculus同时安装，会出现贴图错位的现象（就是乱飞）
![8aa8a41cc4570b56d58fbdf87d62a530_720](https://github.com/user-attachments/assets/0c1e645d-5728-4f51-abb1-91fd18f60179)
![292d0e9402adfc1e9b8face009005924](https://github.com/user-attachments/assets/c25fae54-9f7a-47ae-a0a4-de23b79da7d2)
在已排查完毕其他功能性mod后，删除了oculus，问题得到解决
![e39a806f8059169bd6983cb91c2d7f41_720](https://github.com/user-attachments/assets/89a79f5d-38de-4f4e-96e8-fafb40d10609)
虽然问题解决，但是能修一下吗？
谢谢

**Comment by 286799714** [comment]
是否安装了 HitFeedBack ?

**Comment by TartaricAcid** [comment]
无法复现此问题，关闭
