### ISSUE TITLE
Controllable Mod

### ISSUE THREAD

**Issue by Buttersxx** [MCModderAnchor/TACZ#122]
Please Add support for Mrcrayfish Controllable mod on 1.20.1 forge. Aiming (R2) and shooting (L2) does not work as of now.

**Comment by 286799714** [comment]
Got it, we will implement it the next version

**Comment by Buttersxx** [comment]
Thanks!

**Comment by xQFarGar** [comment]
I have something similar. on version 1.19.2, if you run from controllable and pick up any guns in the world, you will crash

[crash-2025-02-22_23.12.41-client.txt](https://github.com/user-attachments/files/18925582/crash-2025-02-22_23.12.41-client.txt)
