### ISSUE TITLE
连发机制存在Bug，每次连发仅消耗一颗子弹，导致部分武器拥有极其离谱的续航

### ISSUE THREAD

**Issue by Nyakano521** [MCModderAnchor/TACZ#123]
视频：

https://github.com/user-attachments/assets/a6fe4dba-0890-404b-afd1-fe0f02029b18

所有带有连发功能的武器都有这种情况，跟Apex的三重击差不多

**Comment by Nyakano521** [comment]
用此Bug测试了一下M16A4的弹匣总伤，在弹容量均为30发的情况下，结果如下：
单发模式：
![QQ图片20240718224927](https://github.com/user-attachments/assets/fbee3b3d-6b20-414b-aae8-920352a84815)
连发模式：
![QQ图片20240718224952](https://github.com/user-attachments/assets/f5259c8c-0457-47e9-a0d6-804a11c63a83)

**Comment by TartaricAcid** [comment]
多人测试，都无法复现此问题

关闭 Issues
