### ISSUE TITLE
Latest 1.19.2 release crash

### ISSUE THREAD

**Issue by TheWrecker1** [MCModderAnchor/TACZ#129]
just installed the latest 1.19.2 release and im getting this crash: "The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: Timeless & Classics Guns: Zero (tacz) encountered an error during the done event phase" 

Here's the crash report
[crash-2024-07-18_11.09.39-client.txt](https://github.com/user-attachments/files/16286739/crash-2024-07-18_11.09.39-client.txt)

**Comment by TheWrecker1** [comment]
just fixed it

**Comment by CodyMarkix** [comment]
what the hell kind of fix did you do
