### ISSUE TITLE
The Kill Amount is not reset after death

### ISSUE THREAD

**Issue by ArsStels** [MCModderAnchor/TACZ#13]
![image](https://github.com/MCModderAnchor/TACZ/assets/65414135/8a7d43ae-ee18-4cee-88a5-2423e6deed25)
The kill counter is not reset after death.
I would like to see a variable of this value in the game (if it does not exist) public. I mean, so that I can get this value from another plugin on the server and interact with it - give out achievements, awards, and so on.

**Comment by 286799714** [comment]
Kill amount counter is client-side only. If you need the same effect in a server-side plugin, you will need to implement it yourself.

**Comment by ArsStels** [comment]
> Счетчик количества убитых доступен только на стороне клиента. Если вам нужен тот же эффект в серверном плагине, вам нужно будет реализовать его самостоятельно.

Хорошо, спасибо. Я думаю, у меня получится это сделать.
