### ISSUE TITLE
装有刺刀配件的枪械能穿墙攻击

### ISSUE THREAD

**Issue by M0rusi** [MCModderAnchor/TACZ#136]
我测试了默认枪械包内全部四把能装刺刀的武器, 都可以穿过两格实心方块攻击到后方的生物。

**Comment by TartaricAcid** [comment]
修好了

**Comment by TartaricAcid** [comment]
Uploading 1721635569735.mp4…

**Comment by TartaricAcid** [comment]
https://github.com/user-attachments/assets/8a987f4c-07e7-4fea-8059-c8619bd37a51
