### ISSUE TITLE
Gun modelling not visible when first person

### ISSUE THREAD

**Issue by faryun** [MCModderAnchor/TACZ#15]
![2024-06-05_20 26 08](https://github.com/MCModderAnchor/TACZ/assets/43097367/92cf6464-81f1-40ea-8f31-6b2c0d8ce86c)
![2024-06-05_20 26 12](https://github.com/MCModderAnchor/TACZ/assets/43097367/1abe14d3-2db0-41be-9236-60d9aa8ec603)

Why I can't see Guns?

**Comment by faryun** [comment]
I found out why modeling is not visible.
If Video Settings - Graphics : Fabulous!
Gun modelling not visible when first person.

**Comment by TartaricAcid** [comment]
Do not use `Graphics : Fabulous!`
