### ISSUE TITLE
在配置界面修改准星时崩溃

### ISSUE THREAD

**Issue by XiaoQiAWA** [MCModderAnchor/TACZ#16]
在配置界面修改准星并应用时崩溃，这种崩溃是必然的（至少我是这样）
![1717590047_718803_zddv](https://github.com/MCModderAnchor/TACZ/assets/154889886/b5c69f00-0f2b-4eb6-bbb5-7c8f4e3bc77c)
[crash-2024-06-05_20.20.47-client.txt](https://github.com/user-attachments/files/15586845/crash-2024-06-05_20.20.47-client.txt)
[latest.log](https://github.com/user-attachments/files/15586848/latest.log)
[debug.log](https://github.com/user-attachments/files/15586850/debug.log)

**Comment by TartaricAcid** [comment]
你是游戏内按 Alt T 快捷键打开的这个界面，还是游戏外点击 mods 按钮打开的界面

**Comment by XiaoQiAWA** [comment]
游戏外

**Comment by XiaoQiAWA** [comment]
> 你是游戏内按 Alt T 快捷键打开的这个界面，还是游戏外点击 mods 按钮打开的界面
游戏外

**Comment by XiaoQiAWA** [comment]
去除fabric模组仍然会崩
这是去除后的：
[crash-2024-06-06_17.38.12-client.txt](https://github.com/user-attachments/files/15613087/crash-2024-06-06_17.38.12-client.txt)
[latest.log](https://github.com/user-attachments/files/15613098/latest.log)
[debug.log](https://github.com/user-attachments/files/15613099/debug.log)
shedaniel, clothconfig2 PCL给的关键词

**Comment by TartaricAcid** [comment]
已在 hotfix4 中修复
