### ISSUE TITLE
Add aim assist in-game

### ISSUE THREAD

**Issue by youth0530** [MCModderAnchor/TACZ#161]
I would like to see Aim Assist in-game, which is for newbies.
Minecraft's core system is getting close to newbie-friendly day by day, and the gun in-game is a power weapon,
So I'm happy when Aim Assist has been added to the game, which is togglable and configurable in the server. 
This could be changing a wide range of codes, maybe now is not a good time.

Thank you.

**Comment by Luviam** [comment]
Skill Issue

**Comment by youth0530** [comment]
It's so useful to provide aim assist as a legit
Unlike provided by "cheat client" or something

**Comment by youth0530** [comment]
Looks everyone disagree with this idea, so I decided to close this issue.

I gotta think before next time...

**Comment by Devpcgmr** [comment]
I hope tacz devs add aim assist mechanic it feel like playing cod too

**Comment by Mildoverlayed** [comment]
Better idea create one CC tweaked adv prefifials and CC AR is all you need I made one you can find the math you need the bulletkienteics.java

**Comment by Devpcgmr** [comment]
i mean for controller players, it's hard to aim gun with controller, not keyboard and mouse.
there are many cod player are using controller
