### ISSUE TITLE
处于旁观者模式下，可以开枪并且造成伤害。

### ISSUE THREAD

**Issue by AirJerryWhite** [MCModderAnchor/TACZ#17]
[latest.log](https://github.com/user-attachments/files/15605151/latest.log)

**Comment by TartaricAcid** [comment]
该问题无法复现，请再次确认是否正确

**Comment by TartaricAcid** [comment]
测试出来了，单发点射能触发此问题，已修复

**Comment by TartaricAcid** [comment]
已在 hotfix4 中修复
