### ISSUE TITLE
[Bug]: I cant see my gun

### ISSUE THREAD

**Issue by Echrift** [MCModderAnchor/TACZ#177]
So i have 58 mods and timeless and classics zero i try to use the guns but i cant see the gun at all i dont have optifine or any optimization mods. in f3 im holding the gun  but not like its meant to be holded i think that some animation took over the gun holding animation 
![First Person](https://github.com/user-attachments/assets/4679d23c-ce40-4e21-88ae-57f50c536805)
![Third Person](https://github.com/user-attachments/assets/edea99c6-bad8-467d-b6c9-0aa12c291e4b)
Also i cant see the gun when i edit the attachements
Here are the mods i have
![image](https://github.com/user-attachments/assets/b7ad779b-be30-415d-a46f-d184479cdb73)
![image](https://github.com/user-attachments/assets/87ddd6e1-20d2-4b68-97e0-717420991515)
![image](https://github.com/user-attachments/assets/1b14940a-47b3-496f-a04d-adbc966a7a4f)
![image](https://github.com/user-attachments/assets/b249ee57-c7e5-419d-9cab-e27845d99bab)
![image](https://github.com/user-attachments/assets/32c85798-f771-4caa-8471-bb96642388a1)
![image](https://github.com/user-attachments/assets/2fd8ac89-1656-4b9b-8d26-5ca9b73ccb95)
![image](https://github.com/user-attachments/assets/e37b705b-981c-4b5f-b5b2-fe68cb012636)
![image](https://github.com/user-attachments/assets/7079b6e6-67e7-4e03-8b4f-c3fedf72ae36)
![image](https://github.com/user-attachments/assets/ceb55cd6-b000-4d34-9cb2-868af19321f2)
![image](https://github.com/user-attachments/assets/b8cb1eb2-8847-4e12-9435-a94e4af4e67a)
![image](https://github.com/user-attachments/assets/e6b0ba64-410b-4e89-9891-b98029bfe838)
![image](https://github.com/user-attachments/assets/e2affb46-1fb7-464d-b031-bc31b2b15ec6)
![image](https://github.com/user-attachments/assets/1c7933e1-bb18-4287-a380-f715affff435)
![image](https://github.com/user-attachments/assets/824b78f2-41c5-4ddd-93c5-d73e2df0575f)

**Comment by Echrift** [comment]
Please help me

**Comment by KeksStyleDE** [comment]
You have to open your Key Binds and configure the Epic Fight GUI, bind the configuration screen and open it. Go to graphics and Filter Animation, it has to be on. I hope this will fix your problem :)

**Comment by Echrift** [comment]
> You have to open your Key Binds and configure the Epic Fight GUI, bind the configuration screen and open it. Go to graphics and Filter Animation, it has to be on. I hope this will fix your problem :)

Thanks ill try

**Comment by Echrift** [comment]
it worked!
