### ISSUE TITLE
模组弹药无法正常堆叠

### ISSUE THREAD

**Issue by CN-hqjixhf** [MCModderAnchor/TACZ#181]
任何弹药的堆叠数都为1，使用弹药盒可以收集，但是放出时会再次变为1
![image](https://github.com/user-attachments/assets/750b3e78-3bc3-4b4d-85ca-75566bfc5806)
以下是mod列表
![image](https://github.com/user-attachments/assets/922e8999-482a-473f-bd20-d921ed8fa8e7)
![image](https://github.com/user-attachments/assets/5570259c-d08a-453f-b887-f8202eae59f4)
![image](https://github.com/user-attachments/assets/2a254d7a-4963-4f79-9853-c4294a6ee1d7)
![image](https://github.com/user-attachments/assets/4f906c2e-431d-4f7a-b6f7-a8895f1bd169)
![image](https://github.com/user-attachments/assets/750d7e8a-347e-4833-8404-8d1c6a6c05b8)
![image](https://github.com/user-attachments/assets/59bd3fa9-2e92-46e2-8891-b4345ad07f6c)
![image](https://github.com/user-attachments/assets/aa60dd74-5ead-46ff-b97a-44c79cb2b659)
![image](https://github.com/user-attachments/assets/008d0470-f4a8-4931-be02-c43a810fd111)
![image](https://github.com/user-attachments/assets/99ccb8d6-ec6d-4331-bc5e-6446d7bd00b3)
![image](https://github.com/user-attachments/assets/18d6f783-024a-424f-9a83-955bfb7bfdfb)
![image](https://github.com/user-attachments/assets/6a25aacf-3be7-4f4e-bfde-8df994741493)
![image](https://github.com/user-attachments/assets/b772f5e6-dd9d-4021-ab62-872baae295b0)
![image](https://github.com/user-attachments/assets/2cbe26fd-a7c9-4a9f-adb5-2f423858c60b)
问题大概在加入一下mod后出现
![image](https://github.com/user-attachments/assets/e239369b-a96c-4bbc-b349-05e8390ef3c3)
(铷:动态光源,车万女仆,玉 jade,无缝玻璃,是,史蒂夫模型2.2.2,Tweakeroo的forge移植版,Xaero的小地图,oculus,苹果皮)
查看mod配置文件，所有弹药的堆叠数量均无异常，但游戏中依然无法堆叠

**Comment by CN-hqjixhf** [comment]
已查明是Tweakerge导致的无法堆叠，望修复

**Comment by TexBlock** [comment]
请下载[这个模组](https://github.com/ThinkingStudios/TweakergeCompat/releases)，它解决了两者的冲突。

**Comment by 77sew** [comment]
fabric端有一模一样的BUG,我的游戏版本是1.20.1,装了tweakeroo
