### ISSUE TITLE
Where can you find TaCZ 1.0.3?

### ISSUE THREAD

**Issue by imheavi** [MCModderAnchor/TACZ#189]

**Comment by The-idk-notdot** [comment]
same bug

**Comment by qwaasdqw** [comment]
https://afdian.com/a/nekocrane，This is a site similar to Patreon in China。

**Comment by qwaasdqw** [comment]
https://afdian.com/a/nekocrane  This is a site similar to Patreon in China

**Comment by qwaasdqw** [comment]
1.0.3 is in alpha, donations are required to get it.

**Comment by The-idk-notdot** [comment]
> 1.0.3 is in alpha, donations are required to get it.

Still in alpha?

**Comment by qwaasdqw** [comment]
To be honest, I didn't figure out what stage it was in。

**Comment by qwaasdqw** [comment]
Sorry.

**Comment by The-idk-notdot** [comment]
RIP. It's been over a month since 1.0.2 was released.

**Comment by qwaasdqw** [comment]
Version 1.0.3 was not available for public download until three months after its release, and 1.0.3 was released on August 11th.

**Comment by The-idk-notdot** [comment]
What do you mean?

**Comment by The-idk-notdot** [comment]
> Version 1.0.3 was not available for public download until three months after its release, and 1.0.3 was released on August 11th.
The latest tacz version on modrinth/curseforge is 1.0.2

**Comment by The-idk-notdot** [comment]
Bruh you deleted the message

**Comment by qwaasdqw** [comment]
We can't get TACZ for free right now.

**Comment by The-idk-notdot** [comment]
You say that 1.0.3 is ready?

**Comment by The-idk-notdot** [comment]
And we need to wait for september?

**Comment by qwaasdqw** [comment]
I don't know. Maybe October.

**Comment by qwaasdqw** [comment]
But that's just my personal guess.

**Comment by qwaasdqw** [comment]
When version 1.0.3 is released for free, they should upload a video. Promotional video for version 1.0.2: https://www.bilibili.com/video/BV1TS411P7Cs/ (This is a Chinese website similar to youtube)

**Comment by The-idk-notdot** [comment]
Seems like tacz will soon become paid without free releases :|

**Comment by qwaasdqw** [comment]
Why?

**Comment by The-idk-notdot** [comment]
Cause we need to wait 2 months to play public version while we can just pay and play it now, because version was ready in 1 month, not 2.

**Comment by The-idk-notdot** [comment]
Release is ready now, but lets wait 100 years!

**Comment by xjqsh** [comment]
Don't spread rumors. It's just that all the programers have been very busy lately so the development has stalled. 1.0.3 still has some unresolved issues, so it can't be released as a release yet.
