### ISSUE TITLE
快捷栏内有其他物品在枪械工作台前面会出现渲染问题

### ISSUE THREAD

**Issue by XiaoQiAWA** [MCModderAnchor/TACZ#19]
快捷栏内有其他物品在枪械工作台前面会出现渲染问题，如图
![微信截图_20240606175910](https://github.com/MCModderAnchor/TACZ/assets/154889886/843bb98a-6f7e-4279-8803-4abf8345bca6)
[latest.log](https://github.com/user-attachments/files/15613333/latest.log)

**Comment by TartaricAcid** [comment]
这什么渲染问题，我没看出来 XD

**Comment by XiaoQiAWA** [comment]
> 这什么渲染问题，我没看出来 XD

背包显示有东西，但是快捷栏不显示

**Comment by XiaoQiAWA** [comment]
![微信截图_20240607190851](https://github.com/MCModderAnchor/TACZ/assets/154889886/59581feb-2e1f-495e-b584-4ba68732a865)
@TartaricAcid

**Comment by TartaricAcid** [comment]
此问题一直无法复现
