### ISSUE TITLE
New Feature: Add WW2 guns

### ISSUE THREAD

**Issue by Devids10** [MCModderAnchor/TACZ#204]
I've been wondering. Since these gun models sounds and everything is so perfect with this mod, I would love to see an add on or implemented into the mod some old world war 2 weapons such as the iconic M1 Garand, MP40, STG, Thompson and much more only to name a few.

**Comment by Zendyhhhh** [comment]
I have a pack name Operation Zero with WW1 and WW2 guns thats WIP
