### ISSUE TITLE
kubejs配方支持

### ISSUE THREAD

**Issue by EvanHsieh0415** [MCModderAnchor/TACZ#208]
```js
ServerEvents.recipes((event) => {
  event.remove({id: "tacz:ammo/556x45"})
})
```
![圖片](https://github.com/user-attachments/assets/68e01626-0aa8-4a10-becf-5d96dd9f73b8)

**Comment by xjqsh** [comment]
不是bug，枪械工作台配方不走原版配方的加载方式，故无法被kjs操作。请等待后续支持(也许)
