### ISSUE TITLE
开镜灵敏度没效果或者效果不对的bug

### ISSUE THREAD

**Issue by WarmRhombus** [MCModderAnchor/TACZ#21]
版本：tacz-1.20.1-1.0.0-hotfix4-beta
环境：服务器
开镜灵敏度只对装了镜子的枪有效果，但是 装了镜子的枪持枪不开镜也有会开镜灵敏度。
没装镜子就是机瞄的枪，用的是原版灵敏度不管持枪还是开镜都没有开镜灵敏度。
这导致手感非常怪
它应该是不管有没有装镜子的枪右键瞄准都会有开镜灵敏度，持枪的时候应该用的是原版灵敏度

**Comment by 286799714** [comment]
在 [1.0.1-release](https://github.com/MCModderAnchor/TACZ/releases/tag/1.0.1) 版本中修复。
