### ISSUE TITLE
fabric1.20.1版本似乎与sodium有兼容性问题

### ISSUE THREAD

**Issue by MiaoBuJie** [MCModderAnchor/TACZ#210]
每次进入游戏在枪械工作台界面不一会就会闪退，报告说内存不足
[Uploading minecraft-exported-crash-info-2024-09-02T21-12-20.zip…]()

**Comment by xjqsh** [comment]
fabric版本可能暂时没有人维护，不过顺带一提，你的报告看起来上传失败了()

**Comment by MiaoBuJie** [comment]
> fabric版本可能暂时没有人维护，不过顺带一提，你的报告看起来上传失败了（）

好的这样的话只好先等等了，实在感谢。那这边再上传一下报告
[minecraft-exported-crash-info-2024-09-02T21-12-20.zip](https://github.com/user-attachments/files/16842001/minecraft-exported-crash-info-2024-09-02T21-12-20.zip)

**Comment by Misaki-Akeno** [comment]
开了photon和bliss就会出现

**Comment by WANGNIMA912** [comment]
> 开了photon和bliss就会出现

這個問題forge也會有

**Comment by MiaoBuJie** [comment]
还真是光影的问题（倒）
