### ISSUE TITLE
Add Bullet basic physics

### ISSUE THREAD

**Issue by Delelo** [MCModderAnchor/TACZ#213]
Make bullets go down with gravity,
Consider bullet velocity
Make it configurable if whether or not you want "arcade" style of the guns or something more interesting.

 (Bullets dont just teleport to the target that is blocks away from the gun and hits exactly where you are pointing at.)

Similar thing is already done with vanilla arrows, i guess...

**Comment by BlackeagleYT** [comment]
they dont just teleport to a target. They dont hit exacty where you aim at (by default they hit accurately only when aiming ig). You can config all this, gravity, bullet speed, recoil, spread, damage. everything is already configurable.
i guess this is path **config/tacz/custom/tacz_default_pack/guns/data**. Make sure you turn off auto edit by writing /tacz auto write (or smth) off

**Comment by Zendyhhhh** [comment]
Btw they aren't ray cast, yes bullet does have physics and you can customize their velocity
