### ISSUE TITLE
incorrect rendering when holding gun with armour that covers hands

### ISSUE THREAD

**Issue by IshuCute** [MCModderAnchor/TACZ#214]
perhaps it can be fixed by adding a hand position adjustment relative to the weapon. or simply disable hands render in options
![2024-09-08_14 13 33](https://github.com/user-attachments/assets/dd921174-570f-4abe-8aed-3ff7d8fcb09b)
![2024-09-08_14 13 39](https://github.com/user-attachments/assets/7d0f0e9f-052d-49e4-b44d-225480257aef)

**Comment by xjqsh** [comment]
Based on previous reports, this should be caused by some mod conflict. It's not clear what the exact list of mods is

**Comment by IshuCute** [comment]
in game i have only create, ad astra and mekanism with this type of armor. + embedium with additions

**Comment by Daimonfire1** [comment]
Can confirm. Weirdly the bug doesn't exist in 1.0.1 for me, it only started with 1.0.2

**Comment by xjqsh** [comment]
fixed, will be updated in next release
