### ISSUE TITLE
自定义头部hitbox没有效果

### ISSUE THREAD

**Issue by WarmRhombus** [MCModderAnchor/TACZ#22]
版本：tacz-1.20.1-1.0.0-hotfix4-beta
环境：服务器
`HeadShotAABB = ["touhou_little_maid:player [-5.5, 5.0, -5.5, 5.5, 5.5, 5.5]"]`
如果这么写是对的话，那这个自定义头部hitbox没有效果。
我已经保存并重启过服务器。
为了方便看出区别才故意把数值写这么大。

**Comment by TartaricAcid** [comment]
原版玩家的 id 不是 `minecraft:player` 么？

**Comment by WarmRhombus** [comment]
> 原版玩家的 id 不是 `minecraft:player` 么？

原来要加命名空间，我这个是默认生成的，然后改数值
