### ISSUE TITLE
Can aim while running by spamming RMB

### ISSUE THREAD

**Issue by The-idk-notdot** [MCModderAnchor/TACZ#222]
You can aim and reload while running by holding lctrl and spamming RMB
https://github.com/user-attachments/assets/af12d751-3e12-414d-a508-53fab42ddcf6

https://github.com/user-attachments/assets/5863da7b-5cb6-4bbd-b221-c3a4816c0a19

**Comment by The-idk-notdot** [comment]
Its also possible while doing parcool's fast run

**Comment by Chompskydavinchi** [comment]
why is this a problem

**Comment by The-idk-notdot** [comment]
Because its a bug. Its the reason why i am posting this here

**Comment by The-idk-notdot** [comment]
> why is this a problem

its not supposed to be like that

**Comment by Chompskydavinchi** [comment]
Yeah i notice this too but sometimes it gets stuck in the middle of  weapon down anim

**Comment by The-idk-notdot** [comment]
> Yeah i notice this too but sometimes it gets stuck in the middle of weapon down anim

Yeah, pretty sure that its a broken feature
