### ISSUE TITLE
第三人称下 枪管 弹匣等配件 没有正常显示

### ISSUE THREAD

**Issue by fulide** [MCModderAnchor/TACZ#224]
tacz版本：tacz-1.20.1-1.0.2-release
forge版本：1.20.1-Forge_47.3.7
装了oculus 但关闭光影也一样
瞄准镜有正确显示

**Comment by xjqsh** [comment]
为减轻渲染压力，渲染lod模型时故意为之

**Comment by fulide** [comment]
好吧

**Comment by fulide** [comment]
可否在配置文件给个选项 选择渲染或者不渲染呢
