### ISSUE TITLE
[Bug]: TacZ version 1.0.3 fails to load in Quilt/Fabric as its mistaking it for Forge.

### ISSUE THREAD

**Issue by HEALPony** [MCModderAnchor/TACZ#229]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

Minecraft 1.20.1 - Quilt Loader 0.26.3

### tac version

tacz-1.20.1-1.0.3-all

### Related Mods

```raw
n/a
```

### Description

Upon launching the quilt loader version that im using for minecraft (which loads fabric stuff too), im getting an error on the quilt loader stating that the tacz mod is a "forge" version and not a "fabric/quilt" version, yet the name of the tacz file states "all" versions.

### Logs & Crash reports

![image](https://github.com/user-attachments/assets/119760ac-68d7-4ec5-b4f2-029e12145042)

**Comment by xjqsh** [comment]
'-all' means lib included...
