### ISSUE TITLE
[Bug]: Wither can be damaged during his projectile immune phase

### ISSUE THREAD

**Issue by Bebrich** [MCModderAnchor/TACZ#242]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.19.2 forge 43.4.4

### tac version

1.0.3

### Related Mods

```raw
None
```

### Description

You can damage the wither during his wither armor stage, which one expect to not work, as he is immune to the projectiles otherwise.
![image](https://github.com/user-attachments/assets/6ece39ce-c2a7-4783-8290-a4bb4bbc8e20)

### Step to reproduce

Shoot the wither till he is at half health
Shoot him again
Waow

**Comment by xjqsh** [comment]
intented. bullet damage type don't have `projectile` tag so it wont be regarded as 'projectile damage' by default. if u want to make it as 'projectile damage', u can modify the damage type tag via datapack
