### ISSUE TITLE
[Bug]: Increasing the ammo stack size beyond 64 breaks stuff

### ISSUE THREAD

**Issue by Bebrich** [MCModderAnchor/TACZ#247]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.19.2 forge 43.4.4

### tac version

1.0.3

### Related Mods

```raw
tacz
```

### Description

Increasing the ammo stack size beyond 64, lets say 80 for example, allows you to increase the ammo box stack sizes. But, if one tries to retrieve the ammo from the ammo box, the excess 16 ammo are deleted, and 80 item stacks break up once you try to move them inside of your inventory.

**Comment by xjqsh** [comment]
due to the limitations of vanilla mc, the compatibility of modifying the max stack over 64 in vanilla container would be disastrous. Will not consider fixing such issues

**Comment by Bebrich** [comment]
I see some utility in having toolboxes hold more ammo for a specific gun, even just making a ceiling for withdrawing ammo from boxes so that stacks dont get trimmed in a bad way could go a long way
