### ISSUE TITLE
MOD冲突：由MOD:"Blur"造成的枪械改装面板的显示问题

### ISSUE THREAD

**Issue by p0rt39** [MCModderAnchor/TACZ#25]
### 概述
在我同时加载TacZ与一个可以给游戏内菜单界面（如背包）添加虚化背景的MOD:"Blur"一同加载时，
Blur会错误地给TacZ的改装界面添加模糊效果，
虽然**不会带来实质性的功能影响**，但是会导致视觉效果大打折扣。
Blur是一个客户端MOD。
PS:针对相同问题的Issue也正在向MOD:Blur的Github页面提交。
https://github.com/Motschen/Blur/issues/102 (英语)

---

#### Minecraft
使用的Minecraft版本 : 1.20.1
使用的Forge版本 : 47.2.23
#### TacZ
使用的TacZ版本 : [snapshot-2024060613151717679706](https://github.com/MCModderAnchor/TACZ/releases/tag/snapshot-2024060613151717679706)
#### Blur
MC百科页面 : https://www.mcmod.cn/class/1172.html
Github(主分支,已停更) : https://github.com/tterrag1098/Blur
Github(现在的**活跃分支**) : https://github.com/Motschen/Blur

---

### BUG截图
![image](https://github.com/MCModderAnchor/TACZ/assets/122146865/69ab576c-3361-4437-8f46-b173120c70a8)

**Comment by TartaricAcid** [comment]
![image](https://github.com/MCModderAnchor/TACZ/assets/19620085/256f3e2b-3889-4d55-a69d-42c457276c72)
Blur 模组不是有配置文件可以关闭某些 GUI 下的模糊么？？？？？？

**Comment by TartaricAcid** [comment]
你用的应该是 Reblured 模组吧？
找到 Reblured 模组的配置文件，按照如下方式添加 RefitScreen 即可
```
#A list of classes to be excluded from the blur shader.
guiExclusions = [
    "net.minecraft.client.gui.screens.ChatScreen", 
    "net.minecraft.client.gui.screens.InBedChatScreen", 
    "com.tacz.guns.client.gui.GunRefitScreen"
]
```

**Comment by p0rt39** [comment]
> 你用的应该是 Reblured 模组吧？ 找到 Reblured 模组的配置文件，按照如下方式添加 RefitScreen 即可
> 
> ```
> #A list of classes to be excluded from the blur shader.
> guiExclusions = [
>     "net.minecraft.client.gui.screens.ChatScreen", 
>     "net.minecraft.client.gui.screens.InBedChatScreen", 
>     "com.tacz.guns.client.gui.GunRefitScreen"
> ]
> ```

事实上，是Blur(Forge) https://www.curseforge.com/minecraft/mc-mods/blur-forge
我把几个功能相近的mod搞混了。
它的模组配置文件名叫blur，id为Blur(Forge)。
总之，这修复了这个问题。
向您致歉并再次感谢您。
