### ISSUE TITLE
[Bug]: 疾跑可以换弹和开枪

### ISSUE THREAD

**Issue by fzrdwa123456** [MCModderAnchor/TACZ#259]
### 我已确认 ...

- [X] 我正在使用最新版的tacz
- [X] 无法在不安装tacz时复现

### Minecraft和模组加载器版本

minecraft 1.20.1 forge 47.3.10

### tacz的版本

1.0.3

### Related Mods

```raw
没有安装其他的mod
```

### Description

只有tacz

### 复现步骤

大慨就是你疾跑跳跃如何枪械开镜或者换弹反复，任何就会触发一些关于操作逻辑的bug，疾跑貌似会处于枪械的瞄准模式下但是枪械并没有瞄准，其次就是跑的时候比平时要慢很多，但是可以直接一边跑一边开枪和换弹，因为我也不太知道具体的触发条件我只能这么告诉你们按照上面的操作反复就会这样

### 日志和崩溃报告

没有崩溃

**Comment by fzrdwa123456** [comment]
https://github.com/user-attachments/assets/da35672f-1052-49ac-b307-1cedb32fd26a

**Comment by fzrdwa123456** [comment]
按住任意方向键和ctrl和空格疾跑的情况下疯狂的点击左键右键就会出现这个bug，W+ctrl+空格然后右键和左键乱点就会这样，这是我知道最快触发bug的方法

**Comment by fzrdwa123456** [comment]
不按空格也能触发

**Comment by fzrdwa123456** [comment]
话说能把这个bug改进一下吗？例如在配置文件里添加一个开关让玩家换弹的时候也能跑起来

**Comment by xjqsh** [comment]
与 https://github.com/MCModderAnchor/TACZ/issues/222 重复
