### ISSUE TITLE
[Bug]: Using some gunpacks together causes error

### ISSUE THREAD

**Issue by pythoncat1** [MCModderAnchor/TACZ#261]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

Forge 1.20.1 - 47.3.0

### tac version

tacz-1.20.1-1.0.3-release

### Related Mods

```raw
None
```

### Description

When trying to load into a world with many community gun packs installed, an error "invalid player data occurs". This only occurs with specific combinations of gun packs.

### Step to reproduce

1. Install many community gun packs
2. Load into a world
3. The "Invalid player data" error should occur and you should be redirected to the multiplayer server join screen (idk why)

### Logs & Crash reports

None

**Comment by Toppazz** [comment]
ohh yes, same problem on fabric 1.20.1 (0.16.5) singleplayer
tacz-1.20.1-1.0.2

**Comment by qualk** [comment]
Could you post the logs?

**Comment by xjqsh** [comment]
duplicate with https://github.com/MCModderAnchor/TACZ/issues/219

**Comment by pythoncat1** [comment]
> duplicate with #219

Thank you!
