### ISSUE TITLE
[Bug]: freezing when any gun in hands

### ISSUE THREAD

**Issue by Sharaj00** [MCModderAnchor/TACZ#262]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.20.1 Forge-47.3.10

### tac version

1.0.3-all

### Related Mods

```raw
maybe shaders?
photon

First-person Model
```

### Description

just getting periodic lags of 1 to 2 seconds every 3 to 10 seconds and random crash when holding any weapon in hands

### Logs & Crash reports

https://mclo.gs/sFxIlL5

[video](https://drive.google.com/file/d/14vZAoxVWPeVlexxldQLcDrsXwY7JVZTL/view?usp=sharing)

**Comment by qualk** [comment]
Do the lag spikes and crashes happen when there are no shaders loaded? Does it still happen without First-person Model?

**Comment by Sharaj00** [comment]
> Do the lag spikes and crashes happen when there are no shaders loaded? Does it still happen without First-person Model?

it keeps lags with shaders off and first person disabled but less

**Comment by qualk** [comment]
> it keeps lags with shaders off and first person disabled but less

Does just the mod by itself with no other mods present still lag? Does vanilla Minecraft lag?

**Comment by Sharaj00** [comment]
> Does just the mod by itself with no other mods present still lag? Does vanilla Minecraft lag?

after lightening modpack so much lag stopped, but still, weapon in hand beats on performance
