### ISSUE TITLE
[Bug]: Default gun pack can't be changed or overriden

### ISSUE THREAD

**Issue by mpustovoi** [MCModderAnchor/TACZ#267]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

Forge 1.20.1 47.3.10

### tac version

1.0.3

### Related Mods

```raw
None.
```

### Description

I can't override the translations of the default gun pack using my custom resource pack or editing the files in `config\tacz\custom\tacz_default_gun\tacz\lang\`.
I need it to avoid name conflicts with other mods and to add untranslated strings to my language.

In the list of selected resource packs, my custom pack is above everything (meant to override everything), but the default gun pack still uses mod's built-in translations.
![image](https://github.com/user-attachments/assets/83b5a226-9bd5-4c4d-8e06-ad800ea19405)

I guess it's some kind of issue with the load priorities logic.
In addition, it seems every time the game starts, the default gun pack is copied from the mod again and again, making more and more backups each time.

Example of overriding part of the pack via resource pack, `Overrides.zip\assets\tacz\lang\en_us.json`:
```json
{
  "tacz.ammo.12g.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.30_06.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.308.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.338.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.357mag.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.40mm.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.45acp.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.46x30.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.50ae.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.50bmg.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.556x45.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.58x42.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.68x51fury.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.762x25.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.762x39.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.762x54.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.9mm.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.magnum_r.name": "THIS LINE IS OVERRIDEN",
  "tacz.ammo.rpg_rocket.name": "THIS LINE IS OVERRIDEN"
}
```
No changes in game:
![image](https://github.com/user-attachments/assets/3e76f2ce-96ec-469f-9203-b9549a477e45)

Demo pack used: [Overrides.zip](https://github.com/user-attachments/files/17258408/Overrides.zip)

### Step to reproduce

1. Install TACZ
2. Try to override default gun pack translations with a custom resourcepack or try to edit them in config.
3. The default pack loads from mod without any changes and overrides.

### Logs & Crash reports

https://mclo.gs/pupqxQl

**Comment by xjqsh** [comment]
you should change the `DefaultPackDebug` option to `true` in `tacz-common.toml` to edit the default pack.  
 resouce pack override can't take affect due to the way gunpack load now, change that will break compat with all gunpack pervious

**Comment by mpustovoi** [comment]
Thanks.
