### ISSUE TITLE
[Bug]: 穿上通用机械模组的meka装甲时，持枪模型渲染不正确

### ISSUE THREAD

**Issue by RuggedTime** [MCModderAnchor/TACZ#269]
### 我已确认 ...

- [X] 我正在使用最新版的tacz
- [X] 无法在不安装tacz时复现

### Minecraft和模组加载器版本

Forge 47.3.7

### tacz的版本

1.20.1-1.0.3

### Related Mods

```raw
mekanism官方全套（本体+发电机+工具+附加），还附加了一个三方的mekanism weapon模组
```

### Description

身穿meka胸甲持枪时，手部模型渲染有异常位移，遮挡视线且不在标准持枪位置
看样子好像是tacz在翻转手部模型时，没考虑非正常形状的手臂模型？
如果我加上鞘翅单元，发现鞘翅单元新增的手臂模型（一个飞行翼）就正好在原来手应该放的位置

**Comment by RuggedTime** [comment]
![image](https://github.com/user-attachments/assets/42601681-777c-4ddf-925b-b55a4759f17d)
![image](https://github.com/user-attachments/assets/852cad94-d775-41e7-9da5-ac60251fa39d)

**Comment by xjqsh** [comment]
与 https://github.com/MCModderAnchor/TACZ/issues/214 重复
