### ISSUE TITLE
生存模式合成子弹显示问题

### ISSUE THREAD

**Issue by YanZhua** [MCModderAnchor/TACZ#27]
版本1.20.1 1.0.0 hotfix4 ，生存模式下合成子弹后有概率不显示在物品栏中，移动该子弹的合成原料之一后才会显示在物品栏中

**Comment by TartaricAcid** [comment]
已修复，将在下个版本发布

**Comment by 286799714** [comment]
已在 [1.0.1-release](https://github.com/MCModderAnchor/TACZ/releases/tag/1.0.1) 版本中修复。
