### ISSUE TITLE
[Bug]: JEI doesn't reflect correct recipe after changed

### ISSUE THREAD

**Issue by TqLxQuanZ** [MCModderAnchor/TACZ#270]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.20.1-forge-47.3.0

### tac version

1.0.3

### Related Mods

```raw
jei-1.20.1-forge-15.12.2.51.jar
```

### Description

The recipes edited inside the config folder for tacz, doesn't not reflect the JEI recipe correctly. In JEI it's still displaying the default recipe.
![image](https://github.com/user-attachments/assets/2bfbfea6-ee51-430a-b808-8bf2d3405c8c)
![image](https://github.com/user-attachments/assets/23c3561c-4749-4331-9222-83201065aca6)

### Step to reproduce

1. Install JEI and TACZ.
2. Edit TACZ recipes and make sure the default option is off from the config file to prevent overwrite.
3. Get into the game and check the recipe.

**Comment by xjqsh** [comment]
do you use `/tacz reload` to reload the config in game? if so, try restart the game.

**Comment by TqLxQuanZ** [comment]
ah nvm that's my bad, the reload does work. Thanks for the answer!
