### ISSUE TITLE
Items Aren't Stacking Properly and Game Freezes Up During Mod Loading and World Loading

### ISSUE THREAD

**Issue by Coraline774477** [MCModderAnchor/TACZ#272]
Steps to Reproduce the Bug
1. Load the game up and experience the first 1 minute pr so freeze.
2. Create a new world or select a pre-existing world that has TACZ in it.
3. Experience the same freeze again.
4. While in the new world or rhe pre-existing world, have a stackable item in your hot bar
5. place the item (say a fence piece) with right click.
6. break it.
7.will not stack and it's a new item stack.

Expected Behavior
The game not freezing up during mid and world loading as well as items stacking like before.

Actual Behavior
The game freezes during mod loading and world loading and when breaking stackable items (E.G: Oak Fences) thay apparently have a different NBT tag.

Mod Pack URL (Optional)
No response

Mod Pack Version (Optional)
No response

Extra Notes (Optional)
Minecraft: 1.20.1
Forge: 1.20.1-47.3.10
TACZ: 1.0.3

Like say I miss placed a oak plank and I break it, it won't stack with the existing stack and make a new stack of oak planks instead..

During mod loading that after the game reached "mod loading completed" that the game freezes up for a minute. Same happens when loading into the world.

I have took the time to figure out which mod was the corporate that's causing this whole mess and it's the main mod for the world I'm currently playing which is the gun mod TACZ (Timeless and Classics Guns: Zero)..

I think that why its happening in my MineColonies world is possibly coming from the main mod of that world MineColonies...

Before I conducted the tests to see which mod(s) was causing this issue that I had noticed a pattern when starting the game up during mod loading and during world loading which then leads to the main issue of items not stacking properly.

During the tests with just the performance mods installed on a test world that's fresh that I grabbed a stone axe and chopped two blocks of a spruce tree (since I spawned in a taiga biome in the test world) and I was right clicking with the two spruce logs in my hand and placing one back and breaking it again and it did stack.

However, when TACZ is installed I didn't even had to be in the test world because of the patterns at the start before ever entering the test world itself. The freeze during mod loading and world loading was a dead giveaway to the main issue at hand.

One more thing, that's not the latest log, however that log should provide the vital information needed in order to potentially find a solution to this bug.
Also I think that this log was made during my last gaming session.
Since my gaming sessions tends to last till the next day sometimes.

Since the actual latest log doesn't show very much information because I literally just got to the title screen of Minecraft that I'm not in any world just yet.
(However, by the time you read this I'll already be on Cora World: TACZ w/Epic Fight as I craft the guns from TACZ and it's addon mods and the armors from a addon mod for TACZ.)

latest.log
https://gist.github.com/Coraline774477/b3d118fef442c308ca5f5c8e8f746a7f

I copied and heavily modified this report from both JEI's and Sophisticated Backpacks's report issue trackers to fit with TACZ.

Why I decided to go with a blank issue instead of the English issue report that you've set up is because I've copied my issue report from the other issue trackers of JEI and Sophisticated Backpacks that's already highly detailed and has the vital information needed to figure this whole mess out.

**Comment by Coraline774477** [comment]
This is what I said in both issue trackers in the comments to keep Mezz and P3pp3rf1y informed about this while ordeal that I've been going through for almost a week since I started noticing this reoccurring problem;

I'm guessing that itll happen in my MineColonies world as well if I were to try to debunk MineColonies being the corporate to this issue as well...

I'm starting to think that it has something to do with Forge itself...
Lex did his "magic" yet again with certain mods that he screws up when he's updating forge...

Since one forge update screwed up some mods such as Player Companions for an example with bad TPS lag, like really bad that's perpetual with or without the problematic mods installed which forces me to stop playing with those mods and delete my worlds due to the bad TPS lag and now with mods like MineColonies and TACZ that what I've described above happens when they're installed!...

Now I can see why most of the mod authors such as the Twilight Forest devs decided to dump forge for NeoForged...
Since I'm getting sick and tired of Lex's bs and I'm not a mod creator for peet sakes!

**Comment by Coraline774477** [comment]
UPDATE: From P3pp3rf1y telling me that apparently TACZ may be unintentionally using a shortcut and is using getOrCreateTag on all items unintentionally which creates empty nbt tags which make those items different from nbt tags that are set to null.

**Comment by xjqsh** [comment]
pls describe your problem briefly and use the issue template to submit a bug. please understand that most tacz maintainers are not English native speaker, and it's too much torture to read such a long-winded text!

**Comment by Coraline774477** [comment]
So as of the items not stacking properly problem I've finally solved it by removing TACtical Movement mod. As well as Mo' Enchantments mod.

But for the freeze ups during mod loading and world loading I'm unsure of and that's something that you guys will have to fix on your end.

So regarding about me yapping about TACZ being the one that was causing the problem to occur was me losing my gord when the issue started off as of me just simply  blowing it off like it was practically nothing despite the fact that it kept happening over and over again when items didn't stack properly and really wanted to figure out what mod was causing it.

Took me like a week to finally find the corporates that was causing it to happen.

They are: TACtical Movement mod; a abandoned addon mod for TACZ, probably a MCreator mod.

Mo' Enchantments; a enchantments mod that's made with MCreator which was supposed to be like a spiritual successor to Mo Enchants mod which wasn't a MCreator mod.

So I apologize for criticizing TACZ (as well as MineColonies and any other of the main mods I play with on my worlds) for being the corporates of the issue when it wasn't even coming from them to begin with...

Also it wasn't a forge issue either or else it would've been happening with any mod installed. So I don't know exactly why I was accusing Forge of the issue to begin with....

So thank you for closing this ridiculous report that I've made that wasted both of our time that we could've spent on other things instead of this issue report😞

Also I should have used the template to begin with like what you said and I'm dearly sorry😥

**Comment by xjqsh** [comment]
I'm still not sure what's causing your lag, but we've made some optimizations to gun pack loading these days, the speed of reading resources and entering the world should be significantly improved with a lot of gun packs, and this part of the change is included in the next release
