### ISSUE TITLE
[Feature Request]: Gun Safety/Holster

### ISSUE THREAD

**Issue by stevefan1999-personal** [MCModderAnchor/TACZ#274]
Sometimes maybe you don't want to shoot your gun and want to put it down to show yourself as friendly to other players. You turn on the gun safety and there won't be any misfire (or misinput).

This can be simply implemented as one of the fire selection modes which disable shooting and make an "empty click" sound every time you shoot. I haven't been modding MC for 6 years, so I could see if I can be implementing it in a few days. Technically all modern guns have safety (even the good ol' 1911 has it), so this will be an opt-out feature in the data pack.

IRL gun safety should prevent you from pulling the trigger at all, but the implementation scheme mentioned above should be well enough especially with regards to player interaction. 

Optionally, a gun lower/holster animation can also be implemented. When the player is in holster mode, you turn on the gun safety, put the gun down but still be ready to shoot; if the player pressed the shoot button, the weapon will be reactivated (safety's off) and ready to shoot. This means player need to make two mouse clicks in order to make sure to be able to be engaged in battle.

**Comment by Nobody48213** [comment]
Sigma suggestion fr

**Comment by stevefan1999-personal** [comment]
Okay, I just did it but this is awkward:

![image](https://github.com/user-attachments/assets/d717a916-3175-4086-9e6c-86ffba38e784)

This is on a SIG:

![image](https://github.com/user-attachments/assets/17e8d76f-c147-420d-afd8-94932d19173c)


I'm not sure how to best represent this. Maybe I just add a S character to the center of the default texture and call it a day.

At the moment holster animation is yet to be implemented, but I'm looking to use the sprint animation as a starting point.

Problem: when the gun is in holster mode and if the player switch to another hotbar item, how do we blend in the animation smoothly, and what to fo when the player switch from a hotbar item to a previously holsteted weapon?

**Comment by xjqsh** [comment]
While your contribution is appreciated, the safety mode was intentionally removed... I don't think we'll be reintroducing this feature, as for the most part he simply causes unnecessary annoyance, and we've gotten countless reports during the tac age of not being able to fire a gun because the safety wasn't on

**Comment by stevefan1999-personal** [comment]
> While your contribution is appreciated, the safety mode was intentionally removed... I don't think we'll be reintroducing this feature, as for the most part he simply causes unnecessary annoyance, and we've gotten countless reports during the tac age of not being able to fire a gun because the safety wasn't on

Hmm, I need it for a Gmod/FiveM RP style server where police cannot hold gun at people at all times, but I found that interesting it was included before. Still, I work around this by explicitly telling the player the safety's on. That's why I make a click sound and make a big red forbidden icon in the first place. Maybe we need to figure out how to print text when the safety's on as well?

Edit:.Oh right. I added the holster animation because I used to play on a gmod DarkRP server and they use this feature to exactly tell people their gun is on safety.  That's the reason it is added in the first place

**Comment by xjqsh** [comment]
it's a shame that we will not merge this feature in the main fork, if you really need the feature for your server, you can just distribute your build to your players. btw, the safety mode tip is display by `actionbar` messages in tac, as a reference.
