### ISSUE TITLE
这个54R弹是没做完吗

### ISSUE THREAD

**Issue by RogueKGB** [MCModderAnchor/TACZ#279]
看到其他枪包里本来用54R的要么用5.56NATO，要么用M43，就想着去改一下；游戏里的确找到了54R弹，但是枪械工作台没有。去看了一下子弹文件，这是没做完吗(思考.jpg)

我自己尝试着用.308的文件和模型改了一下补全了配置文件，但是游戏里没加载，而且用命令重新加载了以后文件直接重置
![屏幕截图 2024-10-18 215447](https://github.com/user-attachments/assets/67cb5cea-515d-4dda-8e23-702fb8e8fd02)
![屏幕截图 2024-10-19 090410](https://github.com/user-attachments/assets/0bcd5513-3475-421c-a226-30ad9c3f10eb)

**Comment by xjqsh** [comment]
大概是没用上就没实装吧，你要改默认枪包的话要去把 `tacz-common.toml` 里面的`DefaultPackDebug` 选项调成 true, 或者去配置菜单找这个选项
