### ISSUE TITLE
[Bug]: Mod shows double gun model when using first person model

### ISSUE THREAD

**Issue by Kitt012** [MCModderAnchor/TACZ#280]
### I have confirmed that ...

- [x] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

Fabric version 0.5.11

### tac version

1.0.2 - hotfix3

### Related Mods

```raw
First person model 2.4.5 from tr7zw
Timeless and Classics Zero 1.0.2-hotfix3
```

### Description

When I was using Timeless and Classics Zero with First Person Model from tr7zw I noticed

![2024-10-18_21 18 25](https://github.com/user-attachments/assets/a543eb1b-597a-4f6f-b5a7-69ba6493853c)
![2024-10-18_21 18 16](https://github.com/user-attachments/assets/3eef6241-6f4e-4ffa-a601-3f6a65fa0a54)
![2024-10-18_21 18 08](https://github.com/user-attachments/assets/1c54b85b-c9bb-4ead-a46c-ab8172020fcd)

### Step to reproduce

I installed First person model by tr7zw, Timeless and Classics Zero, and porting lib through MultiMC minecraft luancher and then luanched the game and loaded into a world and the player model was holding the gun but when i fired the gun another one would show up on my screen and I do not know why.

### Logs & Crash reports

[FIrst person model bug.txt](https://github.com/user-attachments/files/17442187/FIrst.person.model.bug.txt)

**Comment by xjqsh** [comment]
Due to the way it is implemented, there is no possibility of compatibility...
