### ISSUE TITLE
[Bug]: Hand model becomes glitchy when using netherite backtank in Create with PlayerAnimator mod installed

### ISSUE THREAD

**Issue by IceKube987** [MCModderAnchor/TACZ#284]
### 我已确认 ...

- [X] 我正在使用最新版的tacz
- [X] 无法在不安装tacz时复现

### Minecraft和模组加载器版本

1.20.1 Forge 47.3.5

### tacz的版本

1.20.1 - 1.0.3

### Related Mods

```raw
机械动力(Create)
TaCZ
PlayerAnimator
```

### Description

若安装PlayerAnimator模组，当穿戴机械动力的"下界合金背罐"的时候，手部模型会错位
With the mod _PlayerAnimator_ installed,hand view model becomes glitchy when wearing _Netherite Backtank_ in _Create_
![{26110086-B196-4ECE-8E2D-D50916AF9314}](https://github.com/user-attachments/assets/b83e37b8-0bff-4615-8e53-ca6d5a957583)
![{7EAD2359-D4A7-484B-8EDE-7B49E84D4959}](https://github.com/user-attachments/assets/c7a11d8d-4063-48bb-b174-bbd27b2a145e)
![{141D71F2-7CC5-43E4-825D-638F21DC7200}](https://github.com/user-attachments/assets/1d4d458f-1c07-4e58-9685-140bc8aba661)
![{780A879D-3A5B-4C40-9B95-31B815D6E3B5}](https://github.com/user-attachments/assets/313c90b0-db67-45f1-a589-de0c79b7dffb)

### 复现步骤

1,安装PlayerAnimator
2,穿戴下界合金背罐
3,拿枪

1,Install PlayerAnimator
2,Wear Netherite Backpack
3,Pull out a gun

**Comment by xjqsh** [comment]
已修复，将在下个release更新
