### ISSUE TITLE
[Bug]: Modify Attachments Keybind doesn't work

### ISSUE THREAD

**Issue by BigMartin58** [MCModderAnchor/TACZ#286]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.18.2 Forge 40.2.14

### tac version

1.0.3

### Related Mods

```raw
None
```

### Description

I have tried multiple keybinds and multiple guns, none of which can open the attachments. There are no conflicting keybinds. The keybind doesn't even register in the tooltip of any weapon. It does work for the original TAC, but not for Zero.

**Comment by xjqsh** [comment]
pls send a screenshot of the tooltip and keybinding config screen of the `refit gun` key entry

**Comment by BigMartin58** [comment]
Fixed. I didn't know the refit keybind existed let alone that it was the new attachments keybind. The refit keybind works.
