### ISSUE TITLE
[Bug]: Crash when switching between guns sometimes

### ISSUE THREAD

**Issue by AndrewEllen** [MCModderAnchor/TACZ#287]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.20.1 Forge - 47.3.10

### tac version

tacz-1.20.1-1.0.3-all

### Related Mods

```raw
Oculus Shaders
Embeddium
TACZ
Bliss Shaders (translucent entities off)
```

### Description

Sometimes when switching between TACZ guns with shaders turned on my game crashes giving the error: java.lang.IllegalStateException: Current profile not ended

### Step to reproduce

Install:
- Oculus 1.7.10
- Embeddium 0.3.31
- Bliss Shaders latest dev build from github
- TACZ 1.0.3-all

Switch between guns for a while with shaders on and await the crash. Usually happens within a few minutes

### Logs & Crash reports

[crash-2024-10-24_21.43.26-client.txt](https://github.com/user-attachments/files/17512678/crash-2024-10-24_21.43.26-client.txt)

**Comment by xjqsh** [comment]
~~known, will fix in next release~~
edited: I misread it before, it's not the same issue with the fixed one,
but duplicate with another issue
