### ISSUE TITLE
[Bug]: 左右手切换和开火模式同时快速点击导致稳定闪退

### ISSUE THREAD

**Issue by NULL142857** [MCModderAnchor/TACZ#288]
### 我已确认 ...

- [X] 我正在使用最新版的tacz
- [X] 无法在不安装tacz时复现

### Minecraft和模组加载器版本

1.20.1 Forge 47.3.10

### tacz的版本

1.20.1 - 1.0.3

### Related Mods

```raw
我为了测试单独安装了1.20.1 Forge 47.3.10
并且只装了TACZ模组在MOD文件夹里
其他诸如枪包光影材质数据包，都没有安装
```

### Description

视频展示
视频中我快速点击了【左右手切换】和【更改开火模式】两个按键
随后显示保存世界，后闪退

https://github.com/user-attachments/assets/c0af6e10-7cea-422b-8087-f5239943f5ea

### 复现步骤

不管怎么修改键位，只要拿着枪械在点击【左右手切换】和【更改开火模式】两个按键
并且速度快一点就会导致游戏闪退

### 日志和崩溃报告

[错误报告-2024-10-27_22.19.01.zip](https://github.com/user-attachments/files/17534320/-2024-10-27_22.19.01.zip)

**Comment by xjqsh** [comment]
已知问题，是多线程播放音频引发的CME问题，将在下个版本修复

**Comment by WANGNIMA912** [comment]
抽象bug

**Comment by LiCo16zy** [comment]
> 已知问题，是多线程播放音频引发的CME问题，将在下个版本修复

测试版本: 1.20.1_TacZ_1.1.4, BUG仍然存在, 但触发概率较小

**Comment by xjqsh** [comment]
> > 已知问题，是多线程播放音频引发的CME问题，将在下个版本修复
> 
> 测试版本: 1.20.1_TacZ_1.1.4, BUG仍然存在, 但触发概率较小

发送日志？我这边无法复现

**Comment by LiCo16zy** [comment]
[crash-2025-01-21_11.53.53-client.txt](https://github.com/user-attachments/files/18489464/crash-2025-01-21_11.53.53-client.txt)
这是崩溃报告, 上午随手测试一下这一操作造成了崩溃, 再次启动后反复测试并没有触发, 我不知道这份报告对于分析崩溃原因是否有帮助(我只保存了这个报告), 如果是个乌龙, 还请我提前说一句抱歉.

**Comment by xjqsh** [comment]
> [crash-2025-01-21_11.53.53-client.txt](https://github.com/user-attachments/files/18489464/crash-2025-01-21_11.53.53-client.txt) 这是崩溃报告, 上午随手测试一下这一操作造成了崩溃, 再次启动后反复测试并没有触发, 我不知道这份报告对于分析崩溃原因是否有帮助(我只保存了这个报告), 如果是个乌龙, 还请我提前说一句抱歉.

虽然也是CME但是看起来不是同一个问题，但是看起来不太好调查，我有空去看看
