### ISSUE TITLE
can you add pixelated blood particles?

### ISSUE THREAD

**Issue by trashcan585868** [MCModderAnchor/TACZ#290]
i would like to see particles like in mrcrayfish's gun mod again

**Comment by trashcan585868** [comment]
with a config option by default yes in the client config

**Comment by xjqsh** [comment]
you may try https://www.curseforge.com/minecraft/mc-mods/hit-feedback

**Comment by trashcan585868** [comment]
or i could try: https://www.curseforge.com/minecraft/mc-mods/cravencrafts-bloody-bits for gore!
