### ISSUE TITLE
[Suggestion] Reload Animation speeds increase with Haste and slow down with Mining Fatigue

### ISSUE THREAD

**Issue by HEALPony** [MCModderAnchor/TACZ#292]
Having the ability to customize the players reload animation speeds would be a nice touch for those creating maps and such with the TacZ mod, and I think by using Haste and Mining Fatigue it would make sense for the players reload animation to change depending on the intensity of the effect. Players could set up a beacon with Haste II for a feeling of "Slight of Hand", or if they raid an Ocean Monument and get donged by the Elder Guardian with Mining Fatigue III it should slow their reloads by a substantial amount. I feel like thats fair and would be primarily great for those who are map making with your TacZ mod.

**Comment by xjqsh** [comment]
There are technical issues with the acceleration/deceleration of the animations and sound effects, so we are not going to change the speed of reload in any way for now.
