### ISSUE TITLE
[Bug]: (fabric) not up to date with featured in forge items, bugged scopes, bugged attachment buffs

### ISSUE THREAD

**Issue by 3raz3rr** [MCModderAnchor/TACZ#293]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.20.1 fabric

### tac version

1.20.1-1.0.2-hotfix2 (fabric)

### Related Mods

```raw
cloth-config-11.1.136-fabric
fabric-api-0.92.2+1.20.1
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
tacz-fabric-1.20.1-1.0.2-hotfix2-release
porting_lib-2.3.2+1.20.1
```

### Description

- Mod is missing a bunch of attachments from forge version (not a bug)
- Scope sprites swapped between aiming-not aiming states
![image](https://github.com/user-attachments/assets/96214580-fc7f-4ebb-9f21-9e55ad460ae2)

> stock sights however work fine (in addon packs atleast)

![image](https://github.com/user-attachments/assets/b8c9a553-4e14-40ec-bd67-3a9c08bdde08)

- Attachments doesn't have full list of properties (buffs/debuffs)
![image](https://github.com/user-attachments/assets/420a78fd-6c77-4611-99df-d9690dd14f31)

- Addon pack's attachments missing properties (buffs/debuffs) almost completely
![image](https://github.com/user-attachments/assets/95cdaa6c-f133-4a60-bd14-4e7c5bb98fcd)
![image](https://github.com/user-attachments/assets/c2906e80-e65d-4361-91db-2cd4ceb5276b)
![image](https://github.com/user-attachments/assets/c92c3cce-5b98-47da-961e-b27245c8ce97)

- HE rounds doesn't explode
![image](https://github.com/user-attachments/assets/334a4b5a-ef6c-4524-a248-95ac3066bb2f)
![image](https://github.com/user-attachments/assets/2aab52d3-2da9-44f1-9f1a-eb0d5dfb6bd5)

### Step to reproduce

1. download fabric version of mod
2. Start the game
3. Try to play with the mod

### Logs & Crash reports

[game.log](https://github.com/user-attachments/files/17562449/game.log)

**Comment by xjqsh** [comment]
The fabric branch is maintained by volunteers and its previous maintainer is currently inactive. and we can't do anything about it as we are unfamiliar with fabric...

**Comment by LaeDev** [comment]
> The fabric branch is maintained by volunteers and its previous maintainer is currently inactive. and we can't do anything about it as we are unfamiliar with fabric...

Also, He's not using the latest Fabric release, hotfix-3. i already resovled scope related issue in that version. this issue can be closed.

**Comment by LaeDev** [comment]
it was related iris support. and forge version of tacz is 1.0.3. ofc its not added the newest attachments. still i might fix the attribute problem.

**Comment by xjqsh** [comment]
> > The fabric branch is maintained by volunteers and its previous maintainer is currently inactive. and we can't do anything about it as we are unfamiliar with fabric...
> 
> Also, He's not using the latest Fabric release, hotfix-3. i already resovled scope related issue in that version. this issue can be closed.

got it, thx
