### ISSUE TITLE
我服务器某些功能是收费的，是否可以添加本模组？符合本项目的许可协议吗？

### ISSUE THREAD

**Issue by kamike** [MCModderAnchor/TACZ#295]
我看到项目描述里面说代码遵循 [GNU GPL 3.0]
，资源遵循 [CC BY-NC-ND 4.0]。
假如我在服务器里面添加了这个模组，服务器其他的某些功能收费，是否符合本项目的许可协议？

假如不符合本项目的许可协议，如何获取到资源部分的许可协议呢？可不可以单独申请商业许可协议？？

**Comment by xjqsh** [comment]
原则上我们反对的是提取模组资产挪做他用或者倒卖，如果你只是要使用模组开服，那么就无所谓商不商业，但是枪包作者可能有自己的主张和许可，有些可能对这方面比较敏感甚至过激，这就不是我们能控制的范畴了，如果要用其他枪包的话，避免节外生枝建议先去沟通一下。当然，从个人情感上来讲，我们肯定是反感任何形式的拿模组物品本身去卖(如果你卖的是自己画的皮肤之类的东西不算)和p2w行为的

**Comment by kamike** [comment]
感谢回答，我只是想用这个枪包，但是肯定不会转卖个模组或挪做他用。你所说的枪包作者可能有自己的主张和许可，指的是本模组是由很多人制作的抢包集合吗？所以无法知道其他人的许可协议？还是指的是其他mc枪包模组？

**Comment by xjqsh** [comment]
指的是社区作者做的非官方tacz拓展包，那些内容的许可由他们自己决定
