### ISSUE TITLE
[issue]: How can i /give guns with attachments

### ISSUE THREAD

**Issue by HeavyArtilleryTank** [MCModderAnchor/TACZ#296]
### 我已确认 ...

- [x] 我正在使用最新版的tacz
- [X] 无法在不安装tacz时复现

### Minecraft和模组加载器版本

1.20.1 forge 

### tacz的版本

1.0.3

### Related Mods

```raw
no other mods used
```

### Description

i want to /give an awp with a elcan 4x scope but i dont know how to add an attachment with commands

**Comment by MrPippi** [comment]
try it
`/give @s tacz:modern_kinetic_gun{HasBulletInBarrel: 1b, GunFireMode: "SEMI", GunId: "tacz:ai_awp", AttachmentSCOPE: {id: "tacz:attachment", Count: 1b, tag: {AttachmentId: "tacz:scope_elcan_4x"}}, GunCurrentAmmoCount: 5}`

You can use the `/data get entity @s SelectedItem` command to get the gun data in mainhand

**Comment by HeavyArtilleryTank** [comment]
omg thank you so much. i can finnaly finish my cs2 in minecraft tysm

**Comment by HeavyArtilleryTank** [comment]
btw how can i give guns with other attachments? like a grip or muzzle or mag? anyways tysm

**Comment by HeavyArtilleryTank** [comment]
also what about ammo

**Comment by MrPippi** [comment]
> btw how can i give guns with other attachments? like a grip or muzzle or mag? anyways tysm
You can use the /data get entity @s SelectedItem command to get the gun data in mainhand

> also what about ammo
Ammo: `GunCurrentAmmoCount: 5` `HasBulletInBarrel: 1b`
