### ISSUE TITLE
[Bug]: When using Oculus shaders and then equipping TacZ guns some entities and effects become invisible. After a bit of time. Game will crash

### ISSUE THREAD

**Issue by Darkmega18** [MCModderAnchor/TACZ#297]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.20.1 - Forge - 47.3.11

### tac version

1.0.3

### Related Mods

```raw
born_in_chaos_[Forge]1.20.1_1.5_halloween_event
embeddium-0.3.31+mc1.20.1
geckolib-forge-1.20.1-4.4.9
oculus-mc1.20.1-1.7.0
rubidium-extra-0.5.4.3+mc1.20.1-build.121
tacz-1.20.1-1.0.3-all
```

### Description

I have this issue with a large amount of mods in my main modpack. but testing i trimmed it down to a bare minimum combat mod pack with just the visuals like oculus which I suspect are part of incompatibility and some mobs I noticed which were having issues.

Basically, the game will play fine without shaders and in shaders without touching anything related to tacz.
But once TacZ is pulled out and the custom render or whatever is activated due to using guns or even holding onto ammo, the game may start hitching, some mobs, particularly born in chaos mobs might turn invisible (become unrenderable) and mobs with items in their hands will have their items disappear.

Even after switching from TACZ items there after the game will become unstable and crash after around a minute. Accelerated if guns are constantly picked up and put down repeatedly.

### Step to reproduce

Play game with enclosed modpack. (down in logs)
Use an overworld flatlands for ease of viewing mobs.

Scenario 1:
don't turn on shaders.
Do whatever.
Use guns and fight mobs, all good.
Game should be fine.

Scenario 2:
Turn on shaders, don't use Tacz, also fine.

Scenario 3:
Keep shaders on.
Equip and use tacz items and observe some mobs and/or their items will become unrendered.
Put away tacZ item and continue to observe. Switch in and out to see the mobs appear and disappear.
Eventually, game will crash.
Unsure if it can be saved by turning shaders off then after. But thats beside the point.

### Logs & Crash reports

Most recent crash
[crash-2024-11-03_20.21.42-client.txt](https://github.com/user-attachments/files/17609888/crash-2024-11-03_20.21.42-client.txt)

Most recent latest log
[latest.log](https://github.com/user-attachments/files/17609889/latest.log)

The testing modpack I used. Install with curseforge to test the bug I mentioned. (it's like 24 mods) it contains the shader etc. Maybe try it against some other familiar shaders you might use and see if it's just something to do with this one I've happened to pick out?
https://www.dropbox.com/scl/fi/mlztozbdxeq3akj68ei4h/TacZ-Tester-for-bug-issue-0.0.1.zip?rlkey=bggu8ipwa75m2vz6ngnsbc5fe&st=vjymgl6r&dl=0

**Comment by xjqsh** [comment]
known using photon/bliss shader as well as their derivatives in oculus env with tacz will cause memory leak issue, and we may not able to solve it in the near future, maybe you can try to use other shader at this moment?

**Comment by Darkmega18** [comment]
How do I know which shaders don't use photon/bliss technology then? So I can hunt a different one down?

**Comment by Darkmega18** [comment]
well, spooklementary seems to be working for now. so I guess I'll park myself on spooklementary and tweak it around some.
