### ISSUE TITLE
[Bug]: Ticking player

### ISSUE THREAD

**Issue by Mirtasy** [MCModderAnchor/TACZ#298]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.20.1 forge

### tac version

1.0.3

### Related Mods

```raw
born in chaos 1 1.5 halloween_event
```

### Description

when shooting at mobs from the mod born in chaos the game crashes with the error Ticking player

### Logs & Crash reports

[crash-2024-11-04_19.15.59-server.txt](https://github.com/user-attachments/files/17622418/crash-2024-11-04_19.15.59-server.txt)
[latest.log](https://github.com/user-attachments/files/17622419/latest.log)

**Comment by xjqsh** [comment]
seem to be the born in chaos mod has some bug,  but since it's made by mcr and the decompiled code is really unreadable, maybe you should ask its author if he has any clue?

**Comment by Mirtasy** [comment]
ok. Thx
