### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HeavyArtilleryTank** [MCModderAnchor/TACZ#299]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.20.1 forge 

### tac version

1.0.3

### Related Mods

```raw
NO OTHER MODS USED
```

### Description

how can i /give items wit attachemnts like muzzles magazines and scopes?

**Comment by Type-32** [comment]
In TaCZ, different guns, attachments, and ammo are represented mostly in their NBT data. so e.g. `/give @s tacz:modern_kinetic_gun{GunId:"tacz:m4a1"}` would give you an M4A1. `/give @s tacz:ammo{AmmoId:"tacz:9mm"}` would give you a 9-mil round. It's similar to attachments and you can work this out yourself.

There's a method on how to check what NBT tags are in an item in vanilla Minecraft:
1. Hold the item you want to check
2. Run the command `/data get entity @s SelectedItem.tag` (or something similar, you can search it up)

As far as I can tell, this NBT approach they use is *presumably* for the foundational groundwork of gunpacks customizations.

Hopefully, this answers your question; if you need more support regarding TaCZ, you can get it via their official discord.

**Comment by Type-32** [comment]
Additional comment: I noticed that you made this issue last week: #296 
@MrPippi gave you a good answer, and I would suggest to try explore the mod yourself or finding support on their discord.

**Comment by HeavyArtilleryTank** [comment]
ok but now i am lloking for the muzzles and the other attachments but it just doesnt work

**Comment by Type-32** [comment]
Again, I would suggest to just check the original attachments' properties with the `/data` command, and work your way out from that.

**Comment by HeavyArtilleryTank** [comment]
ok

**Comment by mkp303** [comment]
how would you implement this nbt in a loot table?
I have it like this rn
{
  "type": "minecraft:chest",
  "pools": [
    {
      "rolls": 3,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "tacz:modern_kinetic_gun",
          "weight": 2,
          "quality": 2,
          "functions": [
            {
              "function": "GunId",
              "tag": "tacz:aa12",
              "enchantments": {},
              "add": true,
              "conditions": []
            }
          ]
        }
      ]
    }
  ]
}

**Comment by Type-32** [comment]
@mkp303 This is how you would do it:
```json
{
  "type": "minecraft:chest",
  "pools": [
    {
      "rolls": 3,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "tacz:modern_kinetic_gun",
          "weight": 2,
          "quality": 2,
          "functions": [
            {
              "function": "minecraft:set_nbt",
              "tag": "{GunId:\"tacz:aa12\"}"
            }
          ]
        }
      ]
    }
  ]
}
```

If the TaCZ team didn't add any other Loot Table functions then this should be the vanilla data-driven way to do what you're trying to do. I would suggest you to go check [Misode Github](https://misode.github.io/loot-table/) for their loot table generator. If you're using a mod, it is generally recommended to use the LootTableBuilder instead of the data-driven way, as it would be more convenient to implement stuff in that way (if you're planning on implementing batches of loot tables, that is.)
