### ISSUE TITLE
应该可以优化的小问题

### ISSUE THREAD

**Issue by outtoooo** [MCModderAnchor/TACZ#3]
一些枪械在瞄准的情况下检视显得异常，比如沙鹰按住右键检视时手臂会转
同样的，检视或其他交互时打开改装界面也会显得很奇怪

**Comment by 286799714** [comment]
打开改装界面停止动画播放是一个比较难实现的功能，我觉得不太影响正常的游玩，就没有修。
然后沙鹰瞄准时检视的问题已经在hotfix2中修复。
