### ISSUE TITLE
[Bug]: Fabric版和Zoomify模组有冲突

### ISSUE THREAD

**Issue by cczzyy2020** [MCModderAnchor/TACZ#300]
### 我已确认 ...

- [X] 我正在使用最新版的tacz
- [X] 无法在不安装tacz时复现

### Minecraft和模组加载器版本

Minecraft 1.20.1 & Fabric Loader 0.16.7

### tacz的版本

tacz 1.0.2-hotfix3

### Related Mods

```raw
zoomify 2.14.2+1.20.1
仅添加了tacz和zoomify及必要的库模组
```

### Description

能创建世界，无法进入世界
可能是因为zoomify更改了getZoomDivisor的数据类型：
[‎src/main/kotlin/dev/isxander/zoomify/Zoomify.kt](https://github.com/isXander/Zoomify/commit/77bba8417c4687e20851a011953108c4930da14c#:~:text=fun%20getZoomDivisor(,)%3A%20Float%20%7B)、
[src/main/java/com/tacz/guns/compat/zoomify/ZoomifyCompat.java](https://github.com/We-Cant-Coding/TACZ-Fabric/commit/ccedd29a6e7fd1d20b9746d52eaba1b4ae5438b9#:~:text=public%20static%20double%20getFov(double%20fov%2C%20float%20tickDelta)%20%7B)

### 日志和崩溃报告

```
[14:50:29] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'double dev.isxander.zoomify.Zoomify.getZoomDivisor(float)'
	at com.tacz.guns.compat.zoomify.ZoomifyCompat.getFov(ZoomifyCompat.java:17) ~[tacz-fabric-1.20.1-1.0.2-hotfix3.jar:?]
```

**Comment by xjqsh** [comment]
fabric版本一直是由社区志愿维护，前任维护者现在处于不活跃状态，暂没有人接手，可能没法修了，目前如果可能的话，尝试使用较低版本的zoomify看看？

**Comment by cczzyy2020** [comment]
我fetch了fabric的项目看了下，需要更新下依赖，提交到fabric的issues了
