### ISSUE TITLE
[Enhancement]: Allow Mobs to Hold and Fire Guns

### ISSUE THREAD

**Issue by Spedias** [MCModderAnchor/TACZ#302]
I would love to have this option, even if it was only a limited number of mobs, such as pillagers, skeletons, and/or piglins. Just to provide users with the option of a more immersive PvE experience.

**Comment by 286799714** [comment]
There is already a mod that has mob ai which can hold and fire guns: https://github.com/TartaricAcid/TouhouLittleMaid
We wont provide mob ai in tacz, but writing mob ai in other mods is welcome. If someone is willing to do this, you can refer to TouhouLittleMaid
