### ISSUE TITLE
[Bug]: Adjusting stacksize standerd ammo tacz resets when minecraft gets started

### ISSUE THREAD

**Issue by Lord-Infinity** [MCModderAnchor/TACZ#304]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.20.1 fabric

### tac version

1.0.2.

### Related Mods

```raw
Other weaponpacks that I added and changed the max ammo size did not reset back to standerd size when I started minecraft.
```

### Description

When I adjust the stacksize limit of the standerd tacz ammo it resets back when I start minecraft.

**Comment by xjqsh** [comment]
duplicate to #267
