### ISSUE TITLE
[Bug]: Game crashes when changing between guns (java.lang.OutOfMemoryError: Failed to resize buffer from 2146435072 bytes to -2146435072 bytes)

### ISSUE THREAD

**Issue by SemperFib3rs** [MCModderAnchor/TACZ#309]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

Minecraft 1.20.1 (Forge)

### tac version

tacz-1.20.1-1.0.3-all

### Related Mods

```raw
Oculus
Embeddium

Both using the latest version (as for November 25th 2024) (11/25/2024)
```

### Description

When loading into any world, everything goes just fine
Then, if you pull out a gun, fps drop considerably (in my case, from 90 fps to 60 fps)
There will be sudden fps drops
Game will crash if switching between guns or guns to any vanilla item

Crash report will always state the following:
java.lang.OutOfMemoryError: Failed to resize buffer from 2146435072 bytes to -2146435072 bytes

This I consider very weird considering I have 24GB of Ram (12GB dedicated to Minecraft) and 6GB in VRAM

Here's the mod list:
- TACZ
- Oculus
- Embeddium
- Performance-boosting mods (Ferreticore, Entity Culling, Clumps, BadOptimizations)

I used to have Distant Horizons but removed it to see if it was the problem, but game crashed anyways and logs always confirmed it was never Distant Horizons as a suspected mod for crash

### Step to reproduce

1. Install TACZ, Embeddium, Oculus and use any shaders (I'm using Bliss Shaders with DH compatibility)
2. Load any world and walk around, performance unaffected here
3. Pull out a TACZ gun

### Logs & Crash reports

[crash-2024-11-25_10.49.50-client.txt](https://github.com/user-attachments/files/17906580/crash-2024-11-25_10.49.50-client.txt)
[latest.log](https://github.com/user-attachments/files/17906581/latest.log)
![image](https://github.com/user-attachments/assets/b16e9aec-1442-41fe-9824-c1118ee1b151)

**Comment by LCN650** [comment]
Hello! i have kinda the same problem and the same log about the "Failed to resize buffer.."

**Comment by xjqsh** [comment]
duplicate with https://github.com/MCModderAnchor/TACZ/issues/268
unfortunately, we do not have enough time or energy to solve this issue at present. At the moment it is recommended not to use tacz with bliss/photon
