### ISSUE TITLE
[Feature Request]: 配件绑定功能建议

### ISSUE THREAD

**Issue by ArcHosheri** [MCModderAnchor/TACZ#310]
### 我已确认 ...

- [X] 我正在使用最新版的tacz
- [X] 无法在不安装tacz时复现

### Minecraft和模组加载器版本

1.20.1

### tacz的版本

1.0.3

### Related Mods

```raw
NONE
```

### Description

添加一个配件与枪械绑定的功能，可以是一条指令或附魔，对某些特殊需求的小游戏有所帮助。
一些小游戏设计者会通过添加配件来制定平衡性，但有玩家会从一把枪上偷偷拆卸配件到另一把枪上。

**Comment by xjqsh** [comment]
其实已经有了https://tacwiki.mcma.club/zh/user_guide/attachment_lock/ 不过注意，此功能不是严格的锁定，仅仅是阻止玩家通过正常方式打开改装界面，如果有其他办法强行打开gui(比如某些模组)或者修改nbt是没有办法阻止的
