### ISSUE TITLE
[Bug]: Incompatibility with AAAParticles 

### ISSUE THREAD

**Issue by Sockjr07** [MCModderAnchor/TACZ#315]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

Minecraft version: 1.20.1 Forge version: 47.3.7

### tac version

1.0.3

### Related Mods

```raw
I have over 100 mods, so I'll just list the relevant mods here.
Dawn of the flood
AAAParticles (Dependency for Dawn of the flood)
TacZero
```

### Description

When AAAParticles and TacZero are both installed and enabled, Every gun will be completely black. The guns will still function as normal but it doesn't look right.

### Step to reproduce

Install AAAParticles and TacZero. Give yourself a gun and pull it out. It will be completely black.

**Comment by ChloePrime** [comment]
![image](https://github.com/user-attachments/assets/6adc86a8-2709-486e-b8b4-5cfaff434ccb)
![image](https://github.com/user-attachments/assets/4408e32b-d477-47cd-a4da-7b3b3ab8b32c)
Not Reproduceable :(

**Comment by ChloePrime** [comment]
![image](https://github.com/user-attachments/assets/90813f63-c221-492d-97e5-9d7c838c1889)
![image](https://github.com/user-attachments/assets/774fa0da-7783-4e7e-8b9b-fe1acc24841f)
Even unproduceable when `Dawn of the flood` is installed
