### ISSUE TITLE
[Bug]: Default gun pack did not export correctly on M1 Mac/ AT launcher.

### ISSUE THREAD

**Issue by saucyfat** [MCModderAnchor/TACZ#316]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.20.1 (Forge 47.3.12)

### tac version

1.0.3 and previous

### Related Mods

```raw
Timeless and Classic Zero
```

### Description

Cannot for the life of me get the mod to run on my M1 Mac. Have not been able to reproduce issue on my windows machine which runs TacZ just fine. No other forge mods I have used have had this issue so far.

I have tried multiple times with fresh install  Instances of 1.20.1 without any other mods using AT Launcher. I have used downloading the Jar within the AT launcher mods menu, and also downloading directly from curse forge and modrinth respectively, All yielding the same result.

I tried to reproduce bug on 1.19.2 - game starts but upon trying out in creative, clicking on arrow to second page in creative menu crashes game. 

In 1.20.1, game runs, and can click onto second page and third page. However there is no guns or attachments. The only items that appear in the menu are the shooting targets, workbench and ammo boxes. Which also cannot be interacted with when placed down.

<img width="1440" alt="Screenshot 2024-12-01 at 12 20 06 am" src="https://github.com/user-attachments/assets/e10d44b0-5dfc-47f2-b33e-192210eacdbd">
<img width="1440" alt="Screenshot 2024-12-01 at 12 20 10 am" src="https://github.com/user-attachments/assets/6b24f869-9272-49d8-a407-355e91a7bf76">

One such following log appears during startup, as well as what i suspect all other items producing same log.

[30/11/2024 23:57:45 pm] java.nio.file.NoSuchFileException: config/tacz/custom/tacz_default_gun/tacz/models/gun/lod/m16a1.json
[30/11/2024 23:57:45 pm] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)

I found by looking in config folder, that all the folders for the TacZ mod were created, including subfolders. But no Jsons or other files of the individual guns and attachments are present.

<img width="1282" alt="Screenshot 2024-12-01 at 12 28 15 am" src="https://github.com/user-attachments/assets/6920e725-0ccc-426b-a47a-b1fdcb8186f4">

I have also tried running game with different versions of java, 17 and 21. Both still giving same result.

### Step to reproduce

M1 Mac Sonoma 14.3.1

Install Minecraft 1.20.1 with Forge with AT launcher.

Download TacZ 1.0.3 either from Curseforge, modrinth, or use inbuilt mod downloader of AT launcher.

Play game and see that guns and attachments are missing. Workbench does not present any UI when interacted with. 

### Logs & Crash reports

https://paste.atlauncher.com/view/840b618b-e121-4e7b-97d2-aee0ef2cc1bd

**Comment by xjqsh** [comment]
have no idea about mac as i'm not a mac user... look like there're some folder permission issue and the files not export correctly. 
you can try exporting the default pack of tacz in the .jar (unzip the .jar and you will find it in `assets/tacz/custom/tacz_default_gun`) and put it in the config folder and see if anything change?

**Comment by saucyfat** [comment]
> have no idea about mac as i'm not a mac user... look like there're some folder permission issue and the files not export correctly. you can try exporting the default pack of tacz in the .jar (unzip the .jar and you will find it in `assets/tacz/custom/tacz_default_gun`) and put it in the config folder and see if anything change?

so i just tried this. I unzipped the .jar, and put the tacz_default_gun files into the config. It still does not show up in game and also gives the same java.nio.file.NoSuchFileException: log for the files. Even though the files are there in the directory.

<img width="1214" alt="Screenshot 2024-12-02 at 7 18 00 pm" src="https://github.com/user-attachments/assets/a9011b3e-3f97-4d54-8d82-9862dd4ecb30">


For testing sake I used my windows machine again and created a instance with AT launcher for 1.20.1 with forge. With the TacZ mod. Loading in, it works fine. I then moved the entire instance over onto my M1 Mac and relaunched the game. Again, it gives the same log errors and the items do not show up in game, despite all working on my Windows. 
I've got no clue about modding or these matters at all but I suspect something with the mod is incompatible with ARM java maybe. 

EDIT: I also forgot to mention i tried with fabric as well in the original report, same result occurs.

**Comment by xjqsh** [comment]
emm, it's so weird. unfortunately as none of our dev use mac,  i'm sorry we are not able to troubleshoot this for a while...

**Comment by saucyfat** [comment]
So i tested today some more. I believe the issue lies with AT launcher. I started an instance with 1.20.1 latest forge version on Prism Launcher, behold TacZ works flawlessly. I'm not sure if something was wrong with my installation of AT launcher, since every other forge mod I had used at this point worked fine. But it appears AT launcher was at fault.

**Comment by HazeTheCrux** [comment]
I know this is closed but I am having this issue, and have referred above to possible fixes and it hasn't changed anything
