### ISSUE TITLE
can you add skins?

### ISSUE THREAD

**Issue by trashcan585868** [MCModderAnchor/TACZ#319]
i would like to see skins again to make my gun less realistic looking

**Comment by The-idk-notdot** [comment]
It is planned.

**Comment by trashcan585868** [comment]
darn it!! they mustn't be planned then!!

**Comment by The-idk-notdot** [comment]
Like wtf they were planned like since the start of mod.

**Comment by The-idk-notdot** [comment]
They are closing everything as "not planned", if I contributed.

**Comment by cheesehead5835853853** [comment]
when will skins be added?
