### ISSUE TITLE
[Bug]: i cant load tacz

### ISSUE THREAD

**Issue by yamcheeseball** [MCModderAnchor/TACZ#330]
### I have confirmed that ...

- [x] tacz is up to date
- [ ] unable to reproduce without tacz

### Minecraft and modloader version

1.20.1/forge 47.3.0

### tac version

1.0.2

### Related Mods

```raw
LesRaisins Append Packs
```

### Description

![화면 캡처 2024-12-19 184216](https://github.com/user-attachments/assets/3013a117-3f8d-47cd-ad2e-22313981b0cf)

### Logs & Crash reports

[crash-2024-12-19_18.53.20-fml.txt](https://github.com/user-attachments/files/18195893/crash-2024-12-19_18.53.20-fml.txt)

**Comment by xjqsh** [comment]
seem the verison of leawind_third_person and tacz_leawindtps_compat you installed with tacz is not match, you may try to use another version. 
however, I didn't find the exact combination that would work, you might have to try it yourself
