### ISSUE TITLE
[Bug]: Long time to join servers with 40+ MB of Gunpacks

### ISSUE THREAD

**Issue by Vetpetmon** [MCModderAnchor/TACZ#332]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

Minecraft 1.20.1, Forge 47.3.12

### tac version

1.20.1-1.0.3

### Related Mods

```raw
TACZ
```

### Description

There is no crash, but this does increase the frequency of timing out or dying while logging into dedicated servers due to being stuck in the loading screen.

The default gunpack is approximately 28 MB in size, and other gunpacks can add up to 80+ MB quickly.

Every time a user joins, new or not, they're forced to re-download the packs even if there's no mismatch, this causes logins to a server to take a minute or more, especially on poorer connections.

Proposed solution: Allow servers to disable this check or download step when players log in.

### Step to reproduce

1. Install any combination of gunpacks on both client and server, you can install enough to add on 80 MB for most apparent results
2. Join the server
3. Observe and time how long it takes to load in.

**Comment by Vetpetmon** [comment]
![image](https://github.com/user-attachments/assets/3a9feab2-7492-4a6c-9405-9102cf19e558)
(Image of admin panel, showing 3 custom gunpacks adding ~40 MB)

My current (live) server is using these gunpacks, it would be nice if players didn't have to constantly re-download these & the default since we are using a modpack that provides these already.

**Comment by xjqsh** [comment]
emm, not very sure what u mean by `re-download`?
The gun package itself will not be passed between the server and the client when join the server, the only things that will be synchronized are some data configs of guns.

It does have an issue with unnecessary resource reload occurring when joining worlds or multiplayer though which would cause lag, it should be optimized in the next release.

**Comment by Vetpetmon** [comment]
Thank you! I've had to compensate for players dying while trying to log into the server in the meantime.

**Comment by Vetpetmon** [comment]
Would like to add that this issue also results in a memory leak due to the nature of reloading assets/resources, please notify me with a ping when the next release is made. 👍

**Comment by Vetpetmon** [comment]
Confirmed that 1.1.4 fixed the issue!
