### ISSUE TITLE
在彈匣是滿的情況下還能進行裝彈

### ISSUE THREAD

**Issue by attanlis** [MCModderAnchor/TACZ#34]
如標題
TacZ版本1.0.1
遊戲版本1.20.1
(其實我不太確定這是不是bug欸)

https://github.com/MCModderAnchor/TACZ/assets/172262339/08a94b00-57ec-4ffb-89f6-4c736f09560b

**Comment by 286799714** [comment]
这个不是bug。你调成生存模式就没法这么做了。创造模式能自由换弹是方便调试、观赏。

**Comment by attanlis** [comment]
好的
