### ISSUE TITLE
[Bug]: Game Crashes when switching gun to off-hand position

### ISSUE THREAD

**Issue by BDAthans** [MCModderAnchor/TACZ#342]
### I have confirmed that ...

- [X] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.19.2, Forge 43.4.6

### tac version

tacz-1.19.2-1.0.3-release.jar

### Related Mods

```raw
There isn't a mod indicated that is specifically causing this crashing alongside TACZ. The attached crash log shows there is not a suspected mod causing the crash. The attached crash log also contains the full list of mods within the modpack.
```

### Description

After playing within the game for some time, and having one of the guns from TACZ within the slot, pressing the 'F' key to swap the gun into the off-hand slot, the game crashes. 

Noticed that previously, before one of the crashes, the sounds did not line up with the actions. The fire shot sound was replaced with a minecraft pop sound, and the gun shuffle sound that plays when the gun is selected or unselected, was replaced with another sound as well.

Closing the game and relaunching causes this issue to go away for a little bit of time, but shortly after it returns and then the game crashes again.

The crash log indicates this is likely an issue with the SoundEngine, or possibly other mods utilizing the SoundEngine. The mods IC2 Classic, Ad Astra, and Create Big Cannons all have mixins to the SoundEngine. 

### Step to reproduce

1. Load into the game.
2. Play the game for a bit of time. Time is not specifically consistent.
3. Swap TACZ gun in hand to off-hand slot by pressing 'F' key. 
4. Game crashes and crash log is created.

(NOTE: The crashing is not immediate, but after a little bit of time in game it happens consistently).

### Logs & Crash reports

[crash-2024-12-29_15.47.23-client.txt](https://github.com/user-attachments/files/18271081/crash-2024-12-29_15.47.23-client.txt)

**Comment by BDAthans** [comment]
Updated Forge on the client and on the server from 43.4.6 to 43.4.12. Will report back to see if this at all helps to resolve the problem.

**Comment by xjqsh** [comment]
duplicate with #288, will be fixed in the next release

**Comment by BDAthans** [comment]
Understood. Due to the lack of language localization, English speaking users are not able to understand that this issue has already been reported in chinese. I recommend making it so that there is an english version of the title in the bugs reported.
