### ISSUE TITLE
tacz&Oculus

### ISSUE THREAD

**Issue by GKYASHAN** [MCModderAnchor/TACZ#35]
[crash-2024-06-10_17.58.11-client.txt](https://github.com/user-attachments/files/15760802/crash-2024-06-10_17.58.11-client.txt)
![屏幕截图 2024-06-10 175934](https://github.com/MCModderAnchor/TACZ/assets/102595266/de3aebba-a4d6-434e-99c5-4e5774894c0e)
不好意思，英语不太好，所以直接用中文描述：
我不清楚是否是别的mod引发的bug，可以正常进入游戏，mod枪械使用也没问题，但是每次崩溃貌似都是我朝远处开枪的时候，我尝试过很多次复刻场景，并不是一开枪就会崩溃，扫射很久都没事，但是过一会就会崩溃，
不过这次崩溃不太一样，是我在配置界面点击的时候崩溃的，
平时开枪崩溃pcl提示的都是内存不足，但是我确定我内存是足够的冗余的

**Comment by GKYASHAN** [comment]
我又使用单独的环境测试了一下：
forge; 47.3.1
Embeddium: 0.3.20
Oculus: 1.7.0
tacz: 1.0.1
[crash-2024-06-10_18.13.37-client.txt](https://github.com/user-attachments/files/15763921/crash-2024-06-10_18.13.37-client.txt)

使用ak朝远处，也就是未加载区块的方向连续开枪会崩溃，

**Comment by 286799714** [comment]
你是否在使用photon或者bliss光影包？已知这两个光影包在oculus环境下，与tacz一起运行会导致崩溃。

**Comment by GKYASHAN** [comment]
确实是使用了这两款光影，我试试使用别的光影以及不适用光影会不会出现这一情况。

**Comment by GKYASHAN** [comment]
还有个情况我和你说一下，后来我使用预生成区块这个mod，提前生成了周围较大范围的区块，然后再用枪械向远处区块扫射，扫射时间和前面测试的时间一样，但是就不会崩溃了。光影用的就是photon和bliss，我有进行光影切换测试。所以我怀疑是区块加载的问题？

**Comment by 286799714** [comment]
很好的情报，之后有时间我们会想办法解决。如果还是发生崩溃，就请先使用其他的光影包吧。
