### ISSUE TITLE
1.20.1での Mod Controllableとの互換性の問題

### ISSUE THREAD

**Issue by Lyne410** [MCModderAnchor/TACZ#36]
タイトルは説明不要ですが、基本的に攻撃ボタンと照準ボタンでは銃は発射されません。リロードも出来ません。
MrCrayfish's Guns Modを使用したとき、この問題は起きませんでした。
私はデュアルセンスを使用していますが、L2 を押しても照準が合いません。R2 を押しても発射されず、手を使用しているかのように目の前のブロックが壊れるだけです。修正可能でしょうか？

**Comment by Lyne410** [comment]
The title needs no explanation, but basically the attack and aim buttons disable the gun from firing. Reloading is also disabled.
When I used MrCrayfish's Guns Mod, this problem did not occur.
I am using Dual Sense(PS5 controller)and pressing L2 does not aim, pressing R2 does not fire, and if I select a hand it just breaks the block in front of me. Is it possible to fix this?

**Comment by 286799714** [comment]
メールアドレスを教えていただけますか？修正のために何とか対処します。テストファイルをメールでお送りします。

**Comment by Lyne410** [comment]
ありがとうございます。
masanob.1897@gmail.com までお願いします。

**Comment by mozyu28282828** [comment]
Same here.
TACZ is best ever but the only problem is that.
I need to sit on my couch and play with  controllable mod.
Please support. please...

**Comment by Buttersxx** [comment]
Has this gotten fixed?

**Comment by Lyne410** [comment]
いいえ、まだです
返事を待ってます…

**Comment by Buttersxx** [comment]
I got it to work for my legion go. I can’t get it to work on my main pc.

**Comment by Lyne410** [comment]
Unfortunately I don't have it... but I changed the controllerable key bindings on my PC and for some reason I can no longer sight in with the L2 key on all guns but can reload with the □ key.
And on some guns I can now fire with the R2 key.
Here is what I have found

The ones that can be fired
CZ75
SA58
ACR
LVAR
XM8
KEL TEC-RFB
AUG
M4A1
AKM
Nail Gun
P90
UZI
MP5A5
SMG-45
Vector
PP19
M249
MG42

Other guns cannot be fired.

**Comment by Buttersxx** [comment]
Yeah I figured that out too. I got it to work with my main pc now. I was able to do this with softwares that allow me to change controller buttons. Legion go I used legion space & for my pc I’m using a scuff envision controller & I used icue to change the controller binds. I’m not sure if you can do it with a regular controller. Maybe with AntiMicroX you can change the buttons. I just can’t use parcoor mod now. I’ll be trying to fix that tomorrow.. What I did, was bind LT2 & RT2 to a different keybind in the software. I binded it to the side buttons (button 4 & button 5) of my mouse. Then go controller mod setting and under gameplay unbind Lt2 & Rt2. Then go into your keybinds for your mnk and unbind left button & right button in the gameplay category (for placing & attacking) change those to the keybinds you assigned to LT2 & RT2. Sorry if it doesn’t make sense. It’s late. I’m going to bed.

**Comment by Lyne410** [comment]
Thank you.
I will try it. Good night.

**Comment by Buttersxx** [comment]
I forgot to add. I couldn’t get it to properly work on my main pc.  rt2 & lt2 wouldn’t work correctly. Maybe I did something wrong. I’m going to mess with it more tomorrow. I had to use Rbumper & Lbumper to aim and shoot and rt2 & lt2  for scrolling through the hotbar. But on my legion go. It works normally. If it doesn’t work right for you, like it did me & you have to flip them. Don’t forgot to change the scroll through hotbar controller key binds to rt2 & lt2 under gameplay. if you go that route.
