### ISSUE TITLE
与遥远的地平线(DH)一起使用时存在渲染问题

### ISSUE THREAD

**Issue by xzhao4545** [MCModderAnchor/TACZ#38]
当开启遥远的地平线时，仅手持配镜配件就会导致渲染出现错误，但是持枪或持装配镜的枪，包括开镜都不会有问题。
![Snipaste_2024-06-11_15-35-20](https://github.com/MCModderAnchor/TACZ/assets/133028250/84c2edaf-a305-4bf9-9124-2ac7872d206a)

**Comment by xzhao4545** [comment]
游戏版本1.20.1，且只有启动游戏后第一次进入世界会有这种情况，如果退出到标题后再进入世界就不会有这种问题了。

**Comment by 286799714** [comment]
已知。重新加载资源包或者光影包之类的操作也能让这个问题暂时解决。渲染问题通常都比较难解决，我们目前认为这个问题不太影响正常游玩，所以暂时不会修复
