### ISSUE TITLE
创造模式物品栏出现空栏

### ISSUE THREAD

**Issue by Dr-WeiAL** [MCModderAnchor/TACZ#4]
发现hotfix2仍然没有修复所以来发个issue(
![image](https://github.com/MCModderAnchor/TACZ/assets/47446553/5e670fd7-4576-429c-a521-369aad75564a)
[latest.log](https://github.com/user-attachments/files/15523196/latest.log)

**Comment by TartaricAcid** [comment]
这个是 unknow 枪械的 tab，就是那些写错了枪械类型枪械的标签页，我在考虑要不要删掉这一页，但是这样未来如果有作者写错了东西，他就会发现找不到 tab

**Comment by Dr-WeiAL** [comment]
不显示就说明写错了吧，感觉是没必要留这个空栏

**Comment by XiaoQiAWA** [comment]
我就巧了 第四页完全是空的 没有任何mod的标签页

**Comment by 286799714** [comment]
在 [1.0.1-release](https://github.com/MCModderAnchor/TACZ/releases/tag/1.0.1) 版本中移除了这个标签页。
