### ISSUE TITLE
I get the error "The game crashed while initializing game Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered" when trying to start the game.

### ISSUE THREAD

**Issue by Gatoplayer22** [MCModderAnchor/TACZ#41]
I have tried to download a previous version but I have the same problem, it is a server with mods where it worked perfectly before.
[crash-2024-06-12_00.11.42-client.txt](https://github.com/user-attachments/files/15795398/crash-2024-06-12_00.11.42-client.txt)

**Comment by 286799714** [comment]
There is no useful information in the crash log. It is very likely a mod conflict problem. We have used ModifyArg in the mixin, which is a more compatible way. If there is still a problem, it is beyond our control. You need to find the conflicting mod and delete it.

**Comment by Gatoplayer22** [comment]
how can I use the ModifyArg ?

**Comment by 286799714** [comment]
You need to find the conflicting mod.

**Comment by 3TUSK** [comment]
Technically a duplicate of #7, though I don't have any direct evidence. 

Dev team, please leave this open until #46 (or any other solution) is accepted.
