### ISSUE TITLE
DamageBaseMultiplier对有伤害衰减的枪械不生效

### ISSUE THREAD

**Issue by mobclix** [MCModderAnchor/TACZ#42]
此处是否应该乘以一个 DAMAGE_BASE_MULTIPLIER，使伤害衰减也受此参数影响呢

![PixPin_2024-06-12_15-15-06](https://github.com/MCModderAnchor/TACZ/assets/40229583/625ef216-2e1e-415f-aeab-352f4b7ddf38)

**Comment by 286799714** [comment]
在下个版本修复
