### ISSUE TITLE
Out of Memory Error when using photon shader pack

### ISSUE THREAD

**Issue by TDGXVI** [MCModderAnchor/TACZ#43]
![屏幕截图 2024-06-12 205906](https://github.com/MCModderAnchor/TACZ/assets/87860107/b7fdef7e-c42f-4342-bf4e-b339fb116868)
[crash-2024-06-12_20.58.49-client.txt](https://github.com/user-attachments/files/15805466/crash-2024-06-12_20.58.49-client.txt)
游戏版本 1.20.1 
单机模式运行时TACZ release版本内存占用突然暴涨然后崩溃退出。我的内存为32G。
光影: Photon_v1.0a。
主要模组：机械动力, 遥远地平线

**Comment by 286799714** [comment]
不要用photon

**Comment by TDGXVI** [comment]
在使用Complementary Unbound光影也会出现该问题。

**Comment by 286799714** [comment]
那个版本的 Complementary Unbound？

**Comment by TDGXVI** [comment]
> 不要用photon
那推荐使用哪些光影。

**Comment by TDGXVI** [comment]
> 那个版本的 Complementary Unbound？

5.1.1

**Comment by 286799714** [comment]
目前已知可能冲突的就是photon 和 bliss，其他的你选一个试试，总有没问题的

**Comment by TDGXVI** [comment]
> 目前已知可能冲突的就是photon 和 bliss，其他的你选一个试试，总有没问题的

刚刚测试BSL最新版光影依旧存在崩溃现象，可能不是由于光影出现的错误。

**Comment by TDGXVI** [comment]
如果需要我可以提供Crash Report.

**Comment by 286799714** [comment]
这种崩溃的crash report里面没啥有用的信息。我看了一下报错，和之前遇到的光影冲突是一样的。这个问题先挂起吧，比较稀有

**Comment by TDGXVI** [comment]
> 我看了一下报错，和之前遇到的光影冲突是一样的。这个问题先挂起吧，比较稀有

感谢感谢

**Comment by IceNbrn** [comment]
yup having the same issue with Bliss Shaders
