### ISSUE TITLE
与Hostile Neural Networks模组冲突的问题

### ISSUE THREAD

**Issue by heheda23319** [MCModderAnchor/TACZ#44]
游戏版本1.20.1
neoforge版本47.1.101
永恒枪械工坊：零版本1.01
Hostile Neural Networks版本5.3.0
将永恒枪械工坊的现版本与Hostile Neural Networks一同安装时在加载游戏时会因为永恒枪械工坊：零的ModifyArg注解的索引无效导致崩溃
[crash-2024-06-13_16.20.04-client.txt](https://github.com/user-attachments/files/15816349/crash-2024-06-13_16.20.04-client.txt)

**Comment by 3TUSK** [comment]
和 #7 是同一问题。
