### ISSUE TITLE
Ammo boxes

### ISSUE THREAD

**Issue by Artem4ik-47** [MCModderAnchor/TACZ#47]
Sorry for the question here, but I couldn’t find on the Internet how to put ammo in an ammo box. Please tell me how I can do this.

**Comment by SfortzaPhantom** [comment]
Check official Discord server for reference. Especially Russian section.

**Comment by 286799714** [comment]
In your inventory, left-click and drag the ammo box, then right-click the ammo. close this issue when you dont feel this is a issue anymore

**Comment by Artem4ik-47** [comment]
Thank you so much!
