### ISSUE TITLE
TACZ启动遇到了未知故障，疑似是bug或者兼容问题

### ISSUE THREAD

**Issue by Tracy-Reznik** [MCModderAnchor/TACZ#51]
TACZ启动遇到了未知故障，疑似是bug或者兼容问题
[minecraft-exported-crash-info-2024-06-15T21-29-33.zip](https://github.com/user-attachments/files/15847826/minecraft-exported-crash-info-2024-06-15T21-29-33.zip)

**Comment by 3TUSK** [comment]
是已知问题，但彻底解决需要把 GH-46 移植回 1.19 及 1.18。

**Comment by Tracy-Reznik** [comment]
> 是已知问题，但彻底解决需要把 GH-46 移植回 1.19 及 1.18。

那么这个问题是不是要在下一个版本才能解决呢，好像加了YSM后就会复现，可是我挺想带着YSM一起玩这个mod的

**Comment by 3TUSK** [comment]
> 那么这个问题是不是要在下一个版本才能解决呢

我不是 TaC:Z 的开发者，所以我并没有确切的时间表。请咨询 TaC:Z 的开发团队。

**Comment by Tracy-Reznik** [comment]
好的，那我等后续官方修复好了

**Comment by 286799714** [comment]
solved in https://github.com/MCModderAnchor/TACZ/releases/tag/1.0.2
