### ISSUE TITLE
不知道适合什么不能兼容，也找不到

### ISSUE THREAD

**Issue by sulina2333** [MCModderAnchor/TACZ#53]
[错误报告-2024-6-17_8.06.26.zip](https://github.com/user-attachments/files/15860261/-2024-6-17_8.06.26.zip)

**Comment by 3TUSK** [comment]
是已知问题（#7、#41、#44、#51）。请等待开发组发布新版。

**Comment by 286799714** [comment]
solved in https://github.com/MCModderAnchor/TACZ/releases/tag/1.0.2
