### ISSUE TITLE
Customization Options

### ISSUE THREAD

**Issue by echoless3484** [MCModderAnchor/TACZ#54]
Game Customization Options like:
Infinite Ammo
Free Workbench Items
and more

**Comment by 286799714** [comment]
1. You can use Creative Ammo Box to get infinite ammo.
2. Free Workbench Items option will consider adding.

**Comment by echoless3484** [comment]
Trying to make a ffa gamemode in a server and we can't have everyone on creative as it would be kinda of useless.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
