### ISSUE TITLE
在使用ParCool ! Mod中的快速奔跑功能时手部模型错位

### ISSUE THREAD

**Issue by hfgm1145** [MCModderAnchor/TACZ#56]
在使用ParCool!（即https://www.curseforge.com/minecraft/mc-mods/parcool）  中的快速奔跑功能时手部模型错位，实测所有武器均有此问题，包括绝大多数枪包![2024-06-18_15 24 06](https://github.com/MCModderAnchor/TACZ/assets/134192095/3171078c-7cb2-4ac0-8704-0d370103e31a)
![2024-06-18_15 28 48](https://github.com/MCModderAnchor/TACZ/assets/134192095/43cf9efe-49ac-4f5a-b503-3b7a58a72fa1)

**Comment by sinterde** [comment]
两个解决办法：
1，制作组把动作优先级提高，高到能覆盖掉跑酷的动作
2，改跑酷的配置文件，有一项是Enable Fov Animation，可以关掉第一人称的跑酷动作，第三人称不影响（不过会影响到第一人称的纸娃娃mod）

**Comment by sinterde** [comment]
推荐用“Forge Config Screens”这个模组，在游戏内就可以改配置文件

**Comment by 286799714** [comment]
暂时不会修复这个问题，请修改跑酷模组的配置文件寻求解决。
