### ISSUE TITLE
加入第三人称简易的换弹动作的建议

### ISSUE THREAD

**Issue by sinterde** [MCModderAnchor/TACZ#59]
目前第三人称游玩，只能通过音效和hud判断换弹情况，希望加入一个简单的第三人称换弹动作（就是放低枪械，手随便划拉几下），要是能以换单时间来匹配简易换弹动作的快慢就更好了

**Comment by 286799714** [comment]
考虑到兼容性问题，我们不会制作任何第三人称的人物动画。但是我们有兼容 Yes Steve Model 的计划。如果你希望看到第三人称动画，等兼容后可以配合两个模组使用。
