### ISSUE TITLE
多人游戏下延迟会影响跑射速度

### ISSUE THREAD

**Issue by WarmRhombus** [MCModderAnchor/TACZ#60]
我在本地和服务器里测试发现，高延迟下你的跑射速度会比原本枪械设定的跑射速度要慢不少
这在多人游戏里对高延迟的玩家很不公平

**Comment by 286799714** [comment]
跑射速度指的是？有无视频图片说明？

**Comment by WarmRhombus** [comment]
> 跑射速度指的是？有无视频图片说明？

"sprint_time"的参数
我详细测试了下，同样的武器，”sprint_time“是一样的
不开镜跑射：疾跑后停下显示准星到扣子弹的时间
开镜跑射：疾跑后按下右键开镜到扣子弹的时间
服务器延迟大概80左右
0.283s 本地不开镜跑射
0.25s 本地开镜跑射

0.467s 服务器不开镜跑射
0.449s 服务器开镜跑射

速度几乎两倍差距

**Comment by WarmRhombus** [comment]
> 跑射速度指的是？有无视频图片说明？


> 跑射速度指的是？有无视频图片说明？

另外向前疾跑开镜(按住w和ctrl开镜)，开镜速度确实会比原本正常设定的值要快一点，跑射速度还是跟上面测试的一样

**Comment by TartaricAcid** [comment]
高延迟玩任何游戏都会带来巨大问题

这个问题无法解决
