### ISSUE TITLE
关于多人游戏对枪经常发生同死的原因

### ISSUE THREAD

**Issue by WarmRhombus** [MCModderAnchor/TACZ#61]
这个原因应该跟tacz那个解决了射速不均匀的系统有关，在射出一发子弹后如果你的开火键正在处于激活状态，系统会在射速阈值最短的时间自动帮你射出下一发。
原因：在死亡后的一瞬间系统又帮你射出一发子弹，所以导致经常发生同死

以上的结论仅个人猜测，tacz应该是用了这个设定，如果用了可以在死亡后停止系统的自动开火来解决这个问题

**Comment by WarmRhombus** [comment]
补充：这个应该只跟除半自动模式的武器有关

**Comment by 286799714** [comment]
在 1.0.2 会尝试修复，会添加一个禁止死亡的生物开枪的判定。虽然我觉得这可能不是问题的关键
