### ISSUE TITLE
game crash 1.20.1 out of memory error

### ISSUE THREAD

**Issue by itstooslick** [MCModderAnchor/TACZ#63]
Game crashes with Minecraft 1.20.1, crashes after around on 1 minute giving  out of memory error, when removing the tacz mod the game runs fine.
[Crash Report.txt](https://github.com/user-attachments/files/15934965/New.Text.Document.2.txt)

**Comment by itstooslick** [comment]
if you need more info lemme know, this is my first time reporting a bug on here lol, sorry

**Comment by 286799714** [comment]
Known issue. See https://github.com/MCModderAnchor/TACZ/issues/43
if your are using photon shader pack with tacz, game will crash.

**Comment by itstooslick** [comment]
im using the bliss shader and i just disabled them and it works so yeah must be an issue with that then as well, sorry to disturb!

**Comment by itstooslick** [comment]
either way love the mod! cant wait for a fix, have a great one!
