### ISSUE TITLE
1.18.2渲染及兼容性bug

### ISSUE THREAD

**Issue by nanterdm** [MCModderAnchor/TACZ#64]
体验了一下全新的TacZ，发现做的效果和细节确实不错，但是发现了一点bug：

与其它模组兼容性不佳。经实测发现是滚筒机动(Do a Barrel Roll)与该模组发生了冲突。其它的模组暂且不知道
其次是游戏内的渲染问题。当装载该模组后，玩家与生物的渲染将被附近的方块遮挡。以玩家为中心 半径大约10格的方块将会渲染在实体之上，导致玩家与生物被遮挡。（玩家的渲染被遮挡需第三人称才能看到
第一人称行走的情况下，视角会稍有倾斜，世界的渲染半径会随着步调一会儿近一会儿远的（难以形容该场面
没有装载任何优化mod
装载的mod：
tectonic
BOP
模拟殖民地及其附属
更好的村庄（bettervillage）及其附属
警卫村民（guardvillagers
jei
鼠标手势（MouseTweaks
towns and towers
创世神（worldedit
Xaeros的世界地图
Xaeros的小地图

非常期待TacZ的新版本能够解决这些问题，成为高版本最好的枪械模组

**Comment by 286799714** [comment]
下面两个渲染问题无法确定是tacz引发的

**Comment by 286799714** [comment]
与滚筒飞行的兼容问题修复了 https://github.com/MCModderAnchor/TACZ/releases/tag/1.0.2
