### ISSUE TITLE
Memory Leak using Shaders like Bliss.

### ISSUE THREAD

**Issue by snowleopardd** [MCModderAnchor/TACZ#67]
When you start shooting and using the guns with the shaders, the game will stutter and eventually crash out of memory.

Specs, Mods and info:
3060 12GB, 16GB Ram Ryzen 5 5600, Forge 1.20.1, Mods are: Oculus, Embeddium.

Similar issues with other mainstream shaders:
https://github.com/MCModderAnchor/TACZ/issues/43

**Comment by 286799714** [comment]
This bug is known and we don't have the ability or energy to fix it. Try using a different shaderpack

**Comment by snowleopardd** [comment]
> This bug is known and we don't have the ability or energy to fix it. Try using a different shaderpack

That hurts so much, i thought this was the perfect weapons mod for my modpack but seems like i can't use it, these shaders are my favorite and make the game unique

**Comment by 286799714** [comment]
maybe when we have enough time, we will report the problem to the author of bliss or photon and try to solve it. But for now I can only put this issue aside.
