### ISSUE TITLE
Gunsmith Table -  Rendering Issue 

### ISSUE THREAD

**Issue by ItsSnowia** [MCModderAnchor/TACZ#68]
Not sure what is causing this but the Gunsmith Table causes a lot of strange & bizarre or other words funky visuals while in third-person & first-person.

![image](https://github.com/MCModderAnchor/TACZ/assets/41656501/c3bb2a0f-47e2-4db6-bf0c-40ef0f779bdd)
![image](https://github.com/MCModderAnchor/TACZ/assets/41656501/8a1cf753-5fdc-44ea-b942-9baab0fef045)
![image](https://github.com/MCModderAnchor/TACZ/assets/41656501/3ebd8016-436f-42c5-9170-af1c1933e66d)

**Comment by 286799714** [comment]
Need more information. We have never encountered this situation on the development side. Hope you can find out the specific reason that triggers the problem

**Comment by ItsSnowia** [comment]
> Need more information. We have never encountered this situation on the development side. Hope you can find out the specific reason that triggers the problem

It's normally when I hold the gunsmith table or just have it in my inventory / hotbar but it could be because of a mod out of the 179 in this collection of mods in my modpack that I am unaware that might be incompatible with the TaCZ mod.
if you need my modlist as well as hardware information I can also provide that to get a better understanding.

Here's a quick video showing the visual bug in question
https://youtu.be/KAz049j5i30

**Comment by ItsSnowia** [comment]
My Hardware is:
GPU: Nivida Geforce RTX 3060
CPU: AMD Ryzen 7 5700
RAM: 16 GB(s)
OS: Windows 11


My Modpack consists of:
[FerriteCore ((Neo)Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Caelus API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Hit Feedback (by chloe_koopa)](https://www.curseforge.com/minecraft/mc-mods/hit-feedback)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Radiant Gear (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/radiant-gear)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Origins: Classes (Forge) (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/origins-classes-forge)
[FastConfigAPI (by infinituum17)](https://www.curseforge.com/minecraft/mc-mods/fastconfigapi)
[Hit Indication (by hamesterfoxxo)](https://www.curseforge.com/minecraft/mc-mods/hit-indication)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Artemis' Laboratory Blocks (by Doomed_Artemis)](https://www.curseforge.com/minecraft/mc-mods/artemis-laboratory-blocks)
[Beyond Mines: Falling (by Leonniclass)](https://www.curseforge.com/minecraft/mc-mods/beyond-mines-falling)
[Ore Excavation (by Funwayguy)](https://www.curseforge.com/minecraft/mc-mods/ore-excavation)
[Incapacitated (by MaritheVillain)](https://www.curseforge.com/minecraft/mc-mods/incapacitated)
[You Bandit! (by Eugene2000)](https://www.curseforge.com/minecraft/mc-mods/you-bandit)
[Physics Mod (by haubna)](https://www.curseforge.com/minecraft/mc-mods/physics-mod)
[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Enhanced Armor (by creepermax123)](https://www.curseforge.com/minecraft/texture-packs/enhanced-armor)
[My Minimal Armor (by CountXD)](https://www.curseforge.com/minecraft/texture-packs/minimal-armor-countxd)
[Tissou's Zombie Pack (by Tissou)](https://www.curseforge.com/minecraft/texture-packs/tissous-zombie-pack-optifine-1-7x-1-20)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[PandaLib (by ThePandaOliver)](https://www.curseforge.com/minecraft/mc-mods/pandalib)
[CraftPresence (by CDAGaming_)](https://www.curseforge.com/minecraft/mc-mods/craftpresence)
[CorgiLib (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/corgilib)
[Lootr (Forge & NeoForge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[JumpAnimation (by SaltyWater)](https://www.curseforge.com/minecraft/mc-mods/jumpanimation)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[[EMF] Entity Model Features [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-model-features)
[ThDilos' Customed Fox Origin (by ThDilos)](https://www.curseforge.com/minecraft/mc-mods/thdilos-customed-fox-origin)
[Yeetus Experimentus (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Memory Settings[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/memory-settings)
[Better chunk loading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric)
[Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
[Day Counter (by AntrolGamingOfficial)](https://www.curseforge.com/minecraft/mc-mods/day-counter)
[Durability Tooltip (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/durability-tooltip)
[Cod-Zombies Zombie Voice Pack (by vanima_permai)](https://www.curseforge.com/minecraft/texture-packs/cod-zombies-zombie-voice-pack)
[Nyf's Spiders (by Nyfaria)](https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders)
[Bunker Down (by JAK_the_Cyborg)](https://www.curseforge.com/minecraft/mc-mods/bunker-down)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Timeless and Classics Zero (by nekocrane)](https://www.curseforge.com/minecraft/mc-mods/timeless-and-classics-zero)
[Death Counter (by AntrolGamingOfficial)](https://www.curseforge.com/minecraft/mc-mods/ags-death-counter)
[Underground Bunkers (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/underground-bunkers)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Chunk Sending[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Extra Zombie Drops (by OnMod)](https://www.curseforge.com/minecraft/mc-mods/extra-zombie-drops)
[First Aid (by ichttt)](https://www.curseforge.com/minecraft/mc-mods/first-aid)
[No Hostiles Around Campfire (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire)
[EnhancedVisuals (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/enhancedvisuals)
[Falling Leaves (NeoForge/Forge) (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Security Craft (by Geforce132)](https://www.curseforge.com/minecraft/mc-mods/security-craft)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Emotecraft (Forge) (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/emotecraft-forge)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Dusk[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dusk)
[Zombie Awareness (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/zombie-awareness)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Fast Paintings (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/fast-paintings)
[Ping Wheel (by LukenSkyne)](https://www.curseforge.com/minecraft/mc-mods/ping-wheel)
[Large Ore Deposits (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits)
[Cave Spider Spawn (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/cave-spider-spawn)
[Origins (Forge) (by EdwinMindcraft)](https://www.curseforge.com/minecraft/mc-mods/origins-forge)
[Emissive Vanilla Textures (by nudiscoturkey)](https://www.curseforge.com/minecraft/texture-packs/emissive-vanilla-textures)
[Customizable Player Models (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/custom-player-models)
[Not Enough Animations (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Boss Refreshed (by lukidon)](https://www.curseforge.com/minecraft/texture-packs/boss-refreshed)
[Spiders Produce Webs (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/spiders-produce-webs)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[XL Packets (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/xl-packets)
[YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
[Yung Structures Addon for Loot Integrations (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/yung-structures-addon-for-loot-integrations)
[Tactic Knives PvP (by Beej_Mods)](https://www.curseforge.com/minecraft/texture-packs/tactic-knives-1-16)
[Presence Footsteps [Forge] (by Paint_Ninja)](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge)
[Torch hit! (by CrystalSpider)](https://www.curseforge.com/minecraft/mc-mods/torch-hit)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island)
[Wildfire's Female Gender Mod (Forge) (by WildfireMC)](https://www.curseforge.com/minecraft/mc-mods/female-gender-forge)
[ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[Complementary Shaders - Reimagined (by EminGT)](https://www.curseforge.com/minecraft/shaders/complementary-reimagined)
[Orva Alarms and Sirens (by Orvanic)](https://www.curseforge.com/minecraft/mc-mods/orva-alarms)
[CoroUtil (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/coroutil)
[Better Farmer's Combat (by ElBaronJack)](https://www.curseforge.com/minecraft/mc-mods/better-farmers-combat)
[ImmediatelyFast (by RaphiMC)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast)
[Realistic Combat Soundpack (by Lossvoise)](https://www.curseforge.com/minecraft/texture-packs/realistic-combat-soundpack)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Weather, Storms & Tornadoes (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/weather-storms-tornadoes)
[Sunrise & Sunset Audio (by morgan171040)](https://www.curseforge.com/minecraft/mc-mods/sunrise-sunset-audio)
[Rotted [Forge] (by ASEStefan)](https://www.curseforge.com/minecraft/mc-mods/rotted-forge)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Redirector [Modern] (by pOtAto__bOy)](https://www.curseforge.com/minecraft/mc-mods/redirector)
[Everlasting Skins (by levosssilimo)](https://www.curseforge.com/minecraft/mc-mods/everlasting-skins)
[Weaker day zombie (by Anteria_)](https://www.curseforge.com/minecraft/mc-mods/weaker-day-zombie)
[Jump Over Fences (by Kreezxil)](https://www.curseforge.com/minecraft/mc-mods/jump-over-fences-forge)
[Curious Lanterns (by Psilock1)](https://www.curseforge.com/minecraft/mc-mods/curious-lanterns)
[Labelling Containers (by infinituum17)](https://www.curseforge.com/minecraft/mc-mods/labelling-containers)
[True Darkness [Forge] - Updated Fork (by dylanjkl)](https://www.curseforge.com/minecraft/mc-mods/true-darkness-forge-updated-fork)
[BSL Shaders (by capttatsu)](https://www.curseforge.com/minecraft/shaders/bsl-shaders)
[🎃 Insanity Shader (by ElocinDev)](https://www.curseforge.com/minecraft/shaders/insanity-shader)
[Realistic Explosion Physics (by xBigEllx)](https://www.curseforge.com/minecraft/mc-mods/realistic-explosion-physics)
[Hud Texts (by AntrolGamingOfficial)](https://www.curseforge.com/minecraft/mc-mods/hud-texts)
[Eyes in the Darkness (by gigaherz)](https://www.curseforge.com/minecraft/mc-mods/eyes-in-the-darkness)
[Realm RPG: Fallen Adventurers (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/realm-rpg-fallen-adventurers)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Embeddium (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
[Client Crafting (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/client-crafting)
[Skin Layers 3D (Fabric/Forge) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[No Chat Reports (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Fast Async World Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fast-async-world-save-forge-fabric)
[Loot Integrations[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/loot-integrations)
[Atlas Lib (by smileycorp)](https://www.curseforge.com/minecraft/mc-mods/atlas-lib)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[Chocapic13' Shaders (by Choca_13)](https://www.curseforge.com/minecraft/shaders/chocapic13-shaders)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Fresh Animations (by FreshLX)](https://www.curseforge.com/minecraft/texture-packs/fresh-animations)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Show My Coordinates (by AntrolGamingOfficial)](https://www.curseforge.com/minecraft/mc-mods/show-my-coordinates)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[Simply Swords [Fabric & Forge] (by sweenuss)](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials)
[Illagers Wear Armor (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/illagers-wear-armor)
[Jumpy Boats (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/jumpy-boats)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Simply Light (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/simply-light)
[Pillager's Gun (by Scarasol)](https://www.curseforge.com/minecraft/mc-mods/pillagers-gun)
[Mob Sunscreen (by Kreezxil)](https://www.curseforge.com/minecraft/mc-mods/mob-sunscreen)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[SimplySneak (by SaltyWater)](https://www.curseforge.com/minecraft/mc-mods/simplysneak)
[Embeddium/Rubidium Dynamic Lights (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
[Not Enough Recipe Book [NERB] (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/notenoughrecipebook)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Campfire Spawn and Tweaks (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/campfire-spawn-and-tweaks)
[Sitting+ (by SaltyWater)](https://www.curseforge.com/minecraft/mc-mods/sitting)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Panda's Falling Tree's (by ThePandaOliver)](https://www.curseforge.com/minecraft/mc-mods/pandas-falling-trees)
[It Takes a Pillage (by izofar)](https://www.curseforge.com/minecraft/mc-mods/it-takes-a-pillage)
[Snow Under Trees (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/snow-under-trees)
[Lithostitched (by Apollo)](https://www.curseforge.com/minecraft/mc-mods/lithostitched)
[YDM's Weapon Master (by YourDailyModderx)](https://www.curseforge.com/minecraft/mc-mods/ydms-weapon-master)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[AmbientSounds 6 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[Connected Glass (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/connected-glass)
[Ambient Environment (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/ambient-environment)
[Walkie-Talkie (by Fllaton)](https://www.curseforge.com/minecraft/mc-mods/walkie-talkie)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[Bad Mobs (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bad-mobs)
[Biome Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/biome-music)
[Sun and Moon Celestial Configuration (by InfernalStudios)](https://www.curseforge.com/minecraft/mc-mods/sun-and-moon-celestial-configuration)
[Glowing Ores (Glore) (by Apothicon)](https://www.curseforge.com/minecraft/mc-mods/glowing-ores-glore)
[Villager Names (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples)
[Starter Kit (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/starter-kit)
[No Baby Zombies (by Technicboyman)](https://www.curseforge.com/minecraft/mc-mods/no-baby-zombies)
[Healing Campfire (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/healing-campfire)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Immersive Weathering [FORGE] (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-forge)
[[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Weaker Spiderwebs (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/weaker-spiderwebs)
[Crawl on Demand (by Talilon)](https://www.curseforge.com/minecraft/mc-mods/crawl-on-demand)
[VMH - Variable Mob Height (by Rikurob)](https://www.curseforge.com/minecraft/mc-mods/vmh)
[Euphoria Patches (by SpacEagle17)](https://www.curseforge.com/minecraft/mc-mods/euphoria-patches)

**Comment by 286799714** [comment]
I think you have to check which exactly is the imcompable one. there are too many mods in your mod list

**Comment by ItsSnowia** [comment]
> I think you have to check which exactly is the imcompable one. there are too many mods in your mod list

Yeah, that might be a bit tricky but my guess might be because of Origins, Pehkui, Oculus or Weather2 but can't 100% confirm I'll look into it further later, as there is a lot of mods to go through to troubleshoot, until I can get a proper result I'd have to sit down one of these days and actually go through all 179+ Mods and figure out what is causing the visual issues, and when I do I'll just have reply back with my findings.
