### ISSUE TITLE
标靶车的正面永远只朝向西南方向

### ISSUE THREAD

**Issue by Nyakano521** [MCModderAnchor/TACZ#69]
视频：

https://github.com/MCModderAnchor/TACZ/assets/130070792/c8d2ce90-2ba1-48d2-bc67-0d49e18ad948

造靶场的时候发现的，标靶车的正面总是朝着西南方向，非常难受

**Comment by xjqsh** [comment]
因为原版矿车就是这样的）懒得特地修了，所以我们之前决定下次把这玩意的模型换成两面都有靶子）

**Comment by TartaricAcid** [comment]
![image](https://github.com/MCModderAnchor/TACZ/assets/19620085/a94ab122-a00a-480f-b6e0-a2d56fe1e05e)
解决
