### ISSUE TITLE
Gun models not loading in in first person

### ISSUE THREAD

**Issue by Mushroom969** [MCModderAnchor/TACZ#71]
Gun models wont load in first person view. All of the models work in the inventory or when i drop them on the ground. The forge version is 47.3.1 and the mod version is tacz-1.20.1-1.0.1-hotfix-release.jar. Please help i dont know what to do

**Comment by 286799714** [comment]
Do not set the quality to febulous in the video settings

**Comment by Mushroom969** [comment]
> Do not set the quality to febulous in the video settings
Thanks that worked!

**Comment by Mushroom969** [comment]
Thanks that worked

**Comment by 286799714** [comment]
fixed in 1.0.2
