### ISSUE TITLE
I can't /give any specific weapons

### ISSUE THREAD

**Issue by fragz-creatorcode** [MCModderAnchor/TACZ#76]
Hi! I'm planning on making a server using these guns and I've done something like this before using Mr Crayfish's Gun Mod because all the items had their own name, I really like this mod a lot but I realised that every single gun when I press F3+H have the same name being "tacz:modern_kinetic_gun", maybe there is a work around if i have to give it any tags lets say if I want to give players guns through a command block, or if I'm doing something wrong and there is a way to give specific guns. When I tried to do "/give tacz:"
and then try and to look for the guns, there is a limit of items, I will provide screenshots and it will be definitely appreciated if this can be resolved. 
![image213](https://github.com/MCModderAnchor/TACZ/assets/65070011/dd5038b1-752f-42e9-b63e-0da01f24073a)
![image_2024-06-28_155846623](https://github.com/MCModderAnchor/TACZ/assets/65070011/782b4fb4-c0b8-47b4-b9d5-b23b0b6713fd)

**Comment by 286799714** [comment]
You need to write the nbt for gun item. like 
/give @p tacz:modern_kinetic_gun{GunId:"tacz:ak47"}
