### ISSUE TITLE
Unofficial CustomNPCs port incompatibility

### ISSUE THREAD

**Issue by Goodbird-git** [MCModderAnchor/TACZ#77]
There is an incompatibility between TACZ mod and the unofficial CustomNPCs port (and I'm the one who ported CNPC to 1.20.1), which results in a [crash](https://github.com/user-attachments/files/16039053/crashreport.txt).
The problem is that TACZ mod contains a custom LuaJ scripting engine, which is split into two parts, the jse and the core.
The jse part is registered in the META-INF/jajar/metadata.json, while the core is not registered there. 
CustomNPCs mod supports scripting on any language the engine is installed for. So on start it tried to initiate all of the scripting engines, tries to load the jse part, and does not find the classes from the core part. So the solution would be to register the core part in the META-INF/jajar/metadata.json file, or join both parts together as it was in the official LuaJ 3.0.1. 
For now (in the 0629 version) I made a temporary compatibility fix by just disabling the scripting system if anything went wrong while booting the scripting engines, but I suppose that people would like to use CNPC scripting system with TACZ mod, so it would be really nice if you could fix this issue.

**Comment by 286799714** [comment]
I understand. Now I have uploaded to our private repository and solved the problem. Do you need a build to test? If so, you can leave your email address.

**Comment by Goodbird-git** [comment]
It would be really nice if you could send the test build here 
Tayloringame@gmail.com

**Comment by Goodbird-git** [comment]
Sorry for the late response
Everything works fine now!
Thanks!
