### ISSUE TITLE
在 1.20.1 的快照版本 TaCZ 中，第三方枪械包的动画导致了 com.tacz.guns.client.resource.pojo.model.BonesItem.getPivot() 项返回了 Null 并使游戏崩溃

### ISSUE THREAD

**Issue by SuoHouDaiShi** [MCModderAnchor/TACZ#78]
[crash-2024-06-30_14.12.43-client.txt](https://github.com/user-attachments/files/16043435/crash-2024-06-30_14.12.43-client.txt)
为第三方枪械包导入默认枪械包的 M4A1 动作（未经过修改），导入后在 Forge:Minecraft Progess Done 阶段使游戏崩溃

**Comment by 286799714** [comment]
因为动画里有关键帧的分组，在对应的模型里没有，才会这样

**Comment by SuoHouDaiShi** [comment]
> 因为动画里有关键帧的分组，在对应的模型里没有，才会这样

那么解决方法就是在该模型里添加对应的分组（即使其是空的），对吧……

**Comment by 286799714** [comment]
> 那么解决方法就是在该模型里添加对应的分组（即使其是空的），对吧……

对

**Comment by SuoHouDaiShi** [comment]
> > 那么解决方法就是在该模型里添加对应的分组（即使其是空的），对吧……
> 
> 对

豪德，谢谢你，MayDayMemory（
