### ISSUE TITLE
动画调用的无限递归导致了游戏崩溃

### ISSUE THREAD

**Issue by SuoHouDaiShi** [MCModderAnchor/TACZ#79]
日志
[crash-2024-06-30_21.11.03-client.txt](https://github.com/user-attachments/files/16044761/crash-2024-06-30_21.11.03-client.txt)
模型和动画
[lova.animation.json](https://github.com/user-attachments/files/16044762/lova.animation.json)
[lova_geo.json](https://github.com/user-attachments/files/16044763/lova_geo.json)

**Comment by SuoHouDaiShi** [comment]
补充：这个BUG出现之后会导致存档损坏，删除playerdata也没用

**Comment by 286799714** [comment]
不要把 magazine 分组塞进 additional_magazine 分组下。additional_magazine 分组应该保持干净，它只起定位作用，并且会复制渲染 magazine。如果你把 magazine 分组放在里面，就会死循环。详情见wiki: https://tacwiki.mcma.club/zh/gunpack/animation/#%E5%88%86%E7%BB%84

**Comment by SuoHouDaiShi** [comment]
好的，我以后少犯这样的低级错误（）
