### ISSUE TITLE
Unable to Find Dependency Impl. Repo When Building as Dependency

### ISSUE THREAD

**Issue by Type-32** [MCModderAnchor/TACZ#8]
![image](https://github.com/MCModderAnchor/TACZ/assets/87076491/c2ee0725-cfe7-4f9d-9ab0-d25e4a013700)
![image](https://github.com/MCModderAnchor/TACZ/assets/87076491/6a21efd8-2b5d-4b65-b723-f526a89a88d5)
![image](https://github.com/MCModderAnchor/TACZ/assets/87076491/6427b695-b629-4019-bf30-4066c2b9efd2)

Here is my repo: https://github.com/Type-32/PreciseManufacturing/tree/1.20.1

When using `gradlew build` with the TacZ Mod as a dependency, it fails due to "Could not find com.github.MCModderAnchor:TACZ:${tacz_version}"

In my gradle.properties file I've set my `tacz_version` property to 1.0.0-hotfix2 as indicated in the TacZ source files.

**Comment by TartaricAcid** [comment]
![1](https://github.com/MCModderAnchor/TACZ/assets/19620085/2e3eb673-800f-4f5d-9643-0da646a814ec)
![2](https://github.com/MCModderAnchor/TACZ/assets/19620085/7217cd9a-58a1-4720-9a51-d5eacbc457bf)
![3](https://github.com/MCModderAnchor/TACZ/assets/19620085/0eefe8a4-eac2-449f-a71b-0ed964ba4121)
![4](https://github.com/MCModderAnchor/TACZ/assets/19620085/d5e7cd22-0e45-4a5b-99ac-6a9e54962b28)
![5](https://github.com/MCModderAnchor/TACZ/assets/19620085/6069f691-764f-4f7e-9419-8c3dcce5bfa9)

**Comment by Type-32** [comment]
lol duly noted many thanks :)
