### ISSUE TITLE
incompatible with Oculous in 3rd person

### ISSUE THREAD

**Issue by AlisterGontineac** [MCModderAnchor/TACZ#80]
I noticed if I have Oculous installed when switching to 3rd person, the player model and NPC models float up and to the side.
I've tried removing all my mods to figure it out. 
I didn't see anything about Oculous being incompatible, so I thought I'd drop it here.

**Comment by 286799714** [comment]
Oculus works fine with tacz on my computer. We need more information to diagnose your problem

**Comment by AlisterGontineac** [comment]
Oh I'm sorry, it seems to be "hit feedback" ( https://www.curseforge.com/minecraft/mc-mods/hit-feedback/comments )
I'm sorry for wasting your time, but that also sucks, feels nice when you get a good hit feedback with a sniper.

**Comment by TorchTheDragon** [comment]
I can confirm that Oculus (version 1.7.0) is also causing this issue

With Oculus Installed, No Shader:
![image](https://github.com/MCModderAnchor/TACZ/assets/72819066/776b9f07-6ead-47ed-82ae-c824dbe089c8)

With Oculus Installed, with Shader (using Insanity shader for experiment):
![image](https://github.com/MCModderAnchor/TACZ/assets/72819066/28f6a3e1-8beb-4d11-ad56-914cb40eb456)

Without Oculus Installed:
![image](https://github.com/MCModderAnchor/TACZ/assets/72819066/d8e05d11-a1d8-4a82-9a1b-3a27e10d0e1c)

I do find it interesting though that using a shader actually fixes it.

**Comment by TorchTheDragon** [comment]
Oh wait, I just noticed this comment above, I will check with that

> Oh I'm sorry, it seems to be "hit feedback" ( https://www.curseforge.com/minecraft/mc-mods/hit-feedback/comments ) I'm sorry for wasting your time, but that also sucks, feels nice when you get a good hit feedback with a sniper.

**Comment by TorchTheDragon** [comment]
Hit Feedback (version 1.1.3, NeoForge) disabled and Oculus (version 1.7.0, NeoForge) works, it is an issue on the other mods end
![image](https://github.com/MCModderAnchor/TACZ/assets/72819066/68fd3359-09bb-4588-8886-0c89dd0f298e)
 
![image](https://github.com/MCModderAnchor/TACZ/assets/72819066/3549ef01-4b35-4512-8acf-94a93aac8c92)

**Comment by AlisterGontineac** [comment]
Oh weird, different shaders can cause this? Yeah that's a bummer. Thank you for your time!
