### ISSUE TITLE
First-person Model Mod Compat

### ISSUE THREAD

**Issue by minhduckd5** [MCModderAnchor/TACZ#81]
It would be very nice to have it compatible
Basically 
- The left arm does not hold the grip
- The ADS animation not working but zoom only
- The reload animation neither working
That would be grateful if, it's compatible with FPS-model mod, because I wanna see my body too (i'm using figura and ysm (ysm not compat with fps mod so I'm not saying in here))

**Comment by rino-1830** [comment]
Incomplete solution, but change the Firstperson Model Mod configuration.
Add Timeless&ClassicZero itemIDs to `~/minecraft/config/firstperson.json` > `autoToggleModItems`.

This is the same way to work around rendering issues with mods that change the rendering of vanilla hands, such as EpicFight.

I am not an English speaker, so sorry if the content is incomprehensible to you. :)

**Comment by 286799714** [comment]
> Incomplete solution, but change the Firstperson Model Mod configuration. Add Timeless&ClassicZero itemIDs to `~/minecraft/config/firstperson.json` > `autoToggleModItems`.
> 
> This is the same way to work around rendering issues with mods that change the rendering of vanilla hands, such as EpicFight.
> 
> I am not an English speaker, so sorry if the content is incomprehensible to you. :)

Changing configuration can solve the problem, although it is not perfect solution.

**Comment by minhduckd5** [comment]
> Incomplete solution, but change the Firstperson Model Mod configuration. Add Timeless&ClassicZero itemIDs to `~/minecraft/config/firstperson.json` > `autoToggleModItems`.
> 
> This is the same way to work around rendering issues with mods that change the rendering of vanilla hands, such as EpicFight.
> 
> I am not an English speaker, so sorry if the content is incomprehensible to you. :)

would you mind showing me an example when adding the IDs to the config file... please?

**Comment by devmasu** [comment]
#

> > Incomplete solution, but change the Firstperson Model Mod configuration. Add Timeless&ClassicZero itemIDs to `~/minecraft/config/firstperson.json` > `autoToggleModItems`.
> > This is the same way to work around rendering issues with mods that change the rendering of vanilla hands, such as EpicFight.
> > I am not an English speaker, so sorry if the content is incomprehensible to you. :)
> 
> would you mind showing me an example when adding the IDs to the config file... please?

Hi! Just add "tacz:modern_kinetic_gun" in "autoToggleModItems". 
It should look like this: 
"autoToggleModItems": [
    "exposure:camera",
    "tacz:modern_kinetic_gun"
  ]

**Comment by ArtemFurich** [comment]
@devmasu  у меня вылетает при попытке зайти в minecraft при изменённом файле версия 1 20 1
