### ISSUE TITLE
与动态准星mod不兼容_持枪时无法显示所配置的准星放到副手时则正常显示

### ISSUE THREAD

**Issue by sinterde** [MCModderAnchor/TACZ#82]
https://github.com/MCModderAnchor/TACZ/assets/171409657/9eb8765a-9d7a-41b3-8d72-80c2412329b5
顺便提个内测版的问题，新的第三人称动画头和手臂不会跟随镜头移动，希望能实现原来弩的那套动画机制

**Comment by sinterde** [comment]
与”动态准星“mod不兼容
持枪时无法显示mod配置的准星，放到副手时才能正常显示，在没有第三人称准星的情况下，本来是想着用这个将就的

**Comment by TartaricAcid** [comment]
相关适配已经完成
