### ISSUE TITLE
Low FPS when holding any gun with shaders applied

### ISSUE THREAD

**Issue by imheavi** [MCModderAnchor/TACZ#84]
Whenever I`m not holding a gun, I get around 100 FPS with shaders on. As soon as i hold the on, my FPS drops to around 35-45.

**Comment by sinterde** [comment]
补充：与oculus或embe有冲突，vic的枪械也有同样问题，具体表现为手持有瞄准镜的枪光影会错误，刷新后虽然能回复正常，但帧数会大幅度下降，

**Comment by 286799714** [comment]
Rendering issue is common in mc mod who use high quality model. We are now trying to solve this problem with a new rendering pipeline

**Comment by ghost** [comment]
So is there any solution now? Is there any recommended light and shadow that can be used?
