### ISSUE TITLE
holding attachment in hand triggers error

### ISSUE THREAD

**Issue by dimas1502** [MCModderAnchor/TACZ#85]
everytime i hold a weapon attachment in hand, it triggers OpenGL Error 1826: (invalid framebuffer operation)
restarting the game gets rid of it, but will occur again when doing the same

**Comment by WhiteX0il** [comment]
Turn off GL errors in options
I mean it doesn't fix the issue, something is wrong, but atleast it's hidden.

**Comment by 286799714** [comment]
are you using shaders? try to change a shaderpack or close it

**Comment by dimas1502** [comment]
> are you using shaders? try to change a shaderpack or close it

nope, i never used shaders

also i found out it doesn't just happen by holding it, holding a weapon with an attachment also triggers it

i was also using yes steve model btw

**Comment by TartaricAcid** [comment]
Unable to reproduce this issue, closed
