### ISSUE TITLE
first person gun model not showing

### ISSUE THREAD

**Issue by doddlemadd** [MCModderAnchor/TACZ#88]
i am having issues seeing the actual gun model in firstperson
![20240706183241_1](https://github.com/MCModderAnchor/TACZ/assets/174910609/1528c68f-4baf-4b80-af30-a004958a2e3e)

**Comment by xjqsh** [comment]
Do you use "fabulous" graphics option? if so, try switch to either "fast" or "fancy"

**Comment by 286799714** [comment]
fixed in 1.0.2
