### ISSUE TITLE
cant use mod in multiplayer

### ISSUE THREAD

**Issue by h0tpant5** [MCModderAnchor/TACZ#9]
I have been trying to use the mod in multiplayer server host services, but it happens that when I try to add it it doesn't let me because the option to not let 3rd parties use the mod is activated within the mod configuration in curseforge

**Comment by TartaricAcid** [comment]
What are you talking about? I don't understand it at all. 
**Please provide pictures or videos to describe your problem in detail.**

- This mod can be played on multiplayer servers, which has been tested

**Comment by TartaricAcid** [comment]
![F$6G03VGNPZ8(V0)M7WUFWQ_tmb](https://github.com/MCModderAnchor/TACZ/assets/19620085/5188d2ec-1aff-4fe8-8590-499f3b595db6)
