### ISSUE TITLE
[BUG] taz名称错误，枪械工作台ui有问题

### ISSUE THREAD

**Issue by RuobaiCN** [MCModderAnchor/TACZ#92]
tacz的物品只显示他的代码而不是名字，只有枪械工作台的物品出现这种错误。
枪械工作台的ui有问题按钮的位置与鼠标实际点击的位置不符，通常为鼠标靠下才能点击。

上述问题服务端与客户端均会出现。原因不明

**Comment by TartaricAcid** [comment]
从没有遇到过类似问题，无法复现
