### ISSUE TITLE
生存模式空手碰标靶导致客户端崩溃

### ISSUE THREAD

**Issue by Dr-WeiAL** [MCModderAnchor/TACZ#96]
![image](https://github.com/MCModderAnchor/TACZ/assets/47446553/0ac9ce79-cca3-484f-9007-dae5dc0eee3b)
也有可能是带头的标靶会崩溃？
[crash-2024-07-09_15.46.18-client.txt](https://github.com/user-attachments/files/16142283/crash-2024-07-09_15.46.18-client.txt)

**Comment by TartaricAcid** [comment]
无法复现此问题，我试了没有任何问题

**Comment by Dr-WeiAL** [comment]
怪了，我也没法复现了，等再遇到的时候我再打开吧

**Comment by Dr-WeiAL** [comment]
这边又试了一下，改过名的标靶（带头的）尝试挖的时候会导致崩溃，没有头的就不会崩溃
但是单独测试的时候不会崩溃，先排查一下模组

**Comment by Dr-WeiAL** [comment]
测出来了，在安装了oculus后，空手左键带头的标靶就会导致崩溃
[crash-2024-07-13_14.26.16-client.txt](https://github.com/user-attachments/files/16201158/crash-2024-07-13_14.26.16-client.txt)

**Comment by TartaricAcid** [comment]
![2024-07-19_18 20 05](https://github.com/user-attachments/assets/87e85735-1682-4339-8f2d-0dfe3c91e08c)
依然没问题……

**Comment by Dr-WeiAL** [comment]
忘记补充了
空手碰标靶的下半部分会崩溃，碰上半部分不会崩溃(

**Comment by TartaricAcid** [comment]
![2024-07-19_18 52 10](https://github.com/user-attachments/assets/33cc78ee-415c-45a9-b0da-dd97ea03b7fd)
依然没问题

**Comment by TartaricAcid** [comment]
![2024-07-19_18 53 38](https://github.com/user-attachments/assets/f7e584ee-fa4d-47f6-9293-b522dbbd4d29)
开了光影也没问题

头像会在左键时消失不见，但是不会崩溃，也没有报错

所有不要说是头像显示的问题啊

**Comment by Dr-WeiAL** [comment]
怪了，触发的条件变了，我再排查一下模组(

**Comment by TartaricAcid** [comment]
关闭此 issues，问题多次无法复现
