### ISSUE TITLE
TACZ mod is not applicable in banitem and luckperms plugin

### ISSUE THREAD

**Issue by Ianxyt** [MCModderAnchor/TACZ#97]
All guns have the same item ID of "tacz_modern_kinetic_gun", Please change it. I can't use luckperms and banitem plugins if all guns have the same item ID to bypass specific guns. It always shows to bypass as "banitem.bypass.world.tacz_modern_kinetic_gun.*" I have a server where everyone can hold a gun, but there is a specific gun that they can't hold.

**Comment by ItzEnderArkail** [comment]
if the mod or plugin allows you to add nbt tags to the list, you can block them with their respective tag, for example:
`tacz:modern_kinetic_gun{GunId:"tacz:ak47"}` you can see the id of the gun by typing /data get entity @s SelectedItem when holding certain gun

**Comment by Ianxyt** [comment]
still not working, banitem plugin are only accept vanilla items for nbt tags, do you have discord?

**Comment by TartaricAcid** [comment]
The plugin does not support nbt. This is probably a plugin problem.

We will not fix this issue.
