### ISSUE TITLE
Fabric port ?

### ISSUE THREAD

**Issue by furax124** [MCModderAnchor/TACZ#98]
Maybe a fabric port ?

**Comment by luigi052005** [comment]
I hope we get a fabric port

**Comment by barquitotoxico** [comment]
as the devs said in the discord server, fabric has a lot of limitations compared to forge for porting the mod to fabric

**Comment by TartaricAcid** [comment]
No such plan

**Comment by Schweeeeeeeeeeeeeeee** [comment]
> as the devs said in the discord server, fabric has a lot of limitations compared to forge for porting the mod to fabric

Isnt the whole api ported?

**Comment by luigi052005** [comment]
Fabric >Forge

**Comment by LaeDev** [comment]
Hello! I have attempted to port TacZ to the Fabric loader and have had some success! Here is the related video. It’s not completely finished yet, I will upload the code or release it if the mod's creator gives permission. 

https://youtu.be/4NZpVUrFCqE

**Comment by TartaricAcid** [comment]
@LaeDev amazing, thank you so much
Does fabric have a repo that we can take a look at?

**Comment by furax124** [comment]
> @LaeDev amazing, thank you so much
> 
> Does fabric have a repo that we can take a look at?

https://github.com/We-Cant-Coding/TACZ-Fabric here you go

**Comment by LaeDev** [comment]
> > @LaeDev amazing, thank you so much
> > Does fabric have a repo that we can take a look at?
> 
> https://github.com/We-Cant-Coding/TACZ-Fabric here you go

Already Sended to @TartaricAcid 

Project is Temporary Opened Cause of TartaricAcid.

**Comment by LaeDev** [comment]
https://github.com/We-Cant-Coding/TACZ-Fabric/releases/tag/1.0.0

Finished Porting.

**Comment by sj-hub9796** [comment]
> https://github.com/We-Cant-Coding/TACZ-Fabric/releases/tag/1.0.0
> 
> Finished Porting.

This is amazing :o
thank you for your work!! :D

**Comment by LaeDev** [comment]
> > https://github.com/We-Cant-Coding/TACZ-Fabric/releases/tag/1.0.0
> 
> > 
> 
> > Finished Porting.
> 
> 
> 
> This is amazing :o
> 
> thank you for your work!! :D

모드 이용해주셔서 감사합니다. :)
